### ISSUE TITLE
Neue Icons für Stati der Anfragen

### ISSUE THREAD

**Issue by stadine** [okfde/fragdenstaat_de#105]
[icon-SVG.zip](https://github.com/okfde/fragdenstaat_de/files/1811051/icon-SVG.zip)

**Comment by jfilter** [comment]
Premium.

**Comment by jfilter** [comment]
Bei manchen Icons wie z.B. Antwort verspaetet ist das Hauptsymbol klein und nicht in der Mitte. Gibt's dafuer Gruende? Die Icons sollen ja auch auf mobilen Engeraeten genutzt werden und da sieht man solche Details nicht bzw. sind sie schwer zu erkennen (Stichwort Accessibility). Das Icon fuer die Klassifikation und "Information nicht vorhanden" verstehe ich nicht.

**Comment by stefanw** [comment]
Und es fehlt noch zwei Icons: Anfrage wegen Kosten zurückgezogen und Gebühr erhoben.

**Comment by stadine** [comment]
Ich hol mal ein bisschen aus und erklär erstmal die Logik der Icons. Es gibt auf FragDenStaat vier Stati der Anfragen, die sich erstmal voneinander abgrenzen müssen.

- erfolgreich
- nicht erfolgreich
- in Arbeit
- unklar

Diesen Stati sind wiederum weitere Stati untergeordnet. Vor allem bei „In Arbeit“ haben wir eine bunte Reihe von zusätzlichen Hinweisen (auf die beziehst du dich).

<img width="937" alt="screen shot 2018-03-16 at 00 05 20" src="https://user-images.githubusercontent.com/7421063/37594108-94cd1806-2b74-11e8-9ea8-c22da93423d9.png">

 Alle Icons, die für„In Arbeit“ stehen, deuten daher eine zweite Sprech/Textblase an. Dies bedeutet, dass der E-Mailverlauf noch nicht abgeschlossen ist. 
Die Info, dass die Anfrage nun verspätet beantwortet wurde oder es sich um ein Drittbeteiligungsverfahren handelt, ist meiner Meinung nach eher ein zusäzlicher Hinweis, der sich nicht auf den ganzen Inhalt der Anfragen bezieht und wird daher in dem blauen Punkt rechts oben angezeigt.

Da es Nutzern, die nicht täglich FragDenStaat besuchen, sowieso schwer fallen wird, zehn verschiedene Icons zu unterscheiden, versteh ich sie als Ergänzung zu dem ausgeschriebenen Status. Bei der App/Mobilansicht würde ich darüber nachdenken das Layout so zu ändern, dass der Text die Icons umfließt und die Icons ein bisschen größer zu machen.

Zum Icon „muss klassifiziert werden“:  der Inhalt der Antwort ist bisher unbekannt ist. Deswegen ist der angedeutete Text in gestrichelten Linien und nicht durchgezogen. Der Pfeil soll angeben, dass die Anfrage daher zum Antagssteller zurückgespielt werden muss.
Zum Icon „Information nicht vorhanden“: hier soll die gestrichelte Linie in Kombination mit dem Cursor anzeigen, dass nach dem Dokument gesucht wurde, es aber nicht vorhanden ist.
Wenn du noch Ideen für Alternativen hast, immer her damit. 

@stefanw Die Idee war ja, dass jedes Icon mit dem Icon »Gebühr erhoben« funktioniert. Anbei ist das Eurozeichen alleine. Brauchst du dann noch eins „wegen Kosten zurückgezogen“ oder kann sich das dann aus „Gebühr erhoben“ und „wurde zurückgezogen“ ergeben?
[gebuehr.zip](https://github.com/okfde/fragdenstaat_de/files/1824853/gebuehr.zip)

**Comment by jfilter** [comment]
Mir geht es primär darum wie die Icons für die Stati in der Liste ausehen. Und dafür finde ich wichtig, dass alle Icons konsitent ausehen. Jetzt ist es z.B. so, dass bei *erfolgreich* es nur eine Sprechplase gibt obwohl es ja eine Anfrage und eine Antwort gab. Bei *in Arbeit* sind es zwei Sprechblasen. Zusätzlich sind die Sprechblasen unterschiedlich groß.

Dass man mehrere Icons in eine Kategorie *in Arbeit* guppiert, ist an sich eine gute Idee nur wird das Icon dann sehr komplex. Die Icons, die ich so kenne und nutze (Font Awesome, Material Icons) sind alle sehr simpel. Die sehen z.B. so aus:

![icon-antwort verspatet](https://user-images.githubusercontent.com/3450307/37622731-c7921978-2bc2-11e8-96a6-eaf1e1372ffd.png)

Ich glaube so wird sehr schnell klar um was es geht. Die Sprechblasen liefern für mich keinen Informationsgehalt. Jeder Person sollte klar sein, dass bei einer Liste von Anfragen, die einzelnen Listen-Items jeweils Anfragen sind.

**Comment by stefanw** [comment]
Ich habe das Euro-Zeichen an Anfragen mit Kosten rangehängt.
Leider lässt sich das nicht so gut an den Icons selbst ausrichten, weil alle etwas anders geformt sind. Sieht aber OK aus:

<img width="687" alt="screen shot 2018-03-19 at 22 22 58" src="https://user-images.githubusercontent.com/78356/37623216-3407ce3a-2bc4-11e8-8a5f-01c4e1774689.png">

**Comment by jfilter** [comment]
Niemand hat gesagt, dass die Durchsetzung der Informationsfreiheit in Deutschland einfach wird. Ich gehe jedoch davon aus, dass wir gemeinsam eine für alle zufriedenstellende Lösung finden. Kannst du die Illustrator-Datein hier hochladen?

**Comment by jfilter** [comment]
Moved to https://github.com/okfde/froide-icons.
