### ISSUE TITLE
🇪🇺 Datenschutz-Grundverordnung

### ISSUE THREAD

**Issue by jfilter** [okfde/fragdenstaat_de#109]
Deadline ist der 25.5.2018. Ich würde die neuen Datenschutzbestimmungen gerne schon ein paar Wochen vorher haben, um sie in der App einzuarbeiten. Mit dem Review-Prozess dauert es immer eine Weile bis die Änderungen in der App live sind.

**Comment by arnese** [comment]
Was muss daran denn geändert werden konkret?

**Comment by jfilter** [comment]
Keine Ahnung, da steckt der Teufel im Detail. Aber wenn du das absegnest, ist alles okay. ;)

**Comment by arnese** [comment]
Okay. Hab einige Änderungen gemacht - Beschwerderecht, Datenschutzbeauftragter - kannst du jetzt gern kopieren!

**Comment by jfilter** [comment]
Bester Mann, danke dir.

**Comment by jfilter** [comment]
Wir brauchen ein PIA.

> A Privacy Impact Assessment (PIA), which is required under GDPR for data-intensive projects, is a living document which must be made accessible to all involved with a project. It is the process by which you discuss, audit, inventory, and mitigate the privacy risks inherent in the data you collect and process.
> 
> Like all GDPR documentation, a PIA can be requisitioned by a data protection regulator in the event of a privacy concern or data breach. **Not having a PIA is not an option.**

https://www.smashingmagazine.com/2018/02/gdpr-for-web-developers/#how-does-your-development-workflow-need-to-change
