### ISSUE TITLE
Download unüberprüfter PDF-Dokumente

### ISSUE THREAD

**Issue by maxteufel** [okfde/fragdenstaat_de#111]
Derzeit scheint es leider als Anfragesteller nicht ohne weiteres möglich zu sein, nicht-freigeschaltete PDF-Dokumente herunterzuladen – der Dateiname ist grau. Stattdessen soll man das Dokument "Überprüfen" oder gleich "Freischalten". In manchen Fällen ist das allerdings nicht möglich oder sinnvoll (wenn das komplette Dokument zu schwärzen ist), wie zum Beispiel bei <https://fragdenstaat.de/anfrage/sicherheitsaudits-des-projekts-sichere-implementierung-einer-allgemeinen-kryptobibliothek/> und identischen Anfragen.

Es ist zwar möglich, die Anfrage komplett als ZIP herunterzuladen oder in der HTTP-Anfrage des Schwärzungstools die URL der PDF auszulesen, dies ist allerdings nicht besonders benutzerfreundlich.

**Comment by arnese** [comment]
UI klarer für nicht-öffentliche Anfragen
