### ISSUE TITLE
Geänderte E-Mail Adresse von Kommune

### ISSUE THREAD

**Issue by thannaske** [okfde/fragdenstaat_de#112]
Hi,

meine [Anfrage](https://fragdenstaat.de/anfrage/messdaten-der-geschwindigkeitsmessanlagen-im-stadtgebiet/) ist leider auf Grund einer nicht länger vorhandenen E-Mail Adresse zurück gekommen. Laut der Webseite ist die Adresse nicht mehr magistrat@ sondern nun vielmehr info@.

Es wäre gut, wenn die Adresse im System aktualisiert werden könnte. Ich habe leider die Datensätze nicht in Github gefunden, sonst hätte ich einen PR aufgemacht.

Grüße,
Tobias

**Comment by arnese** [comment]
Danke! Done.
