### ISSUE TITLE
Behörden-Datenbank erweitern

### ISSUE THREAD

**Issue by arnese** [okfde/fragdenstaat_de#116]
FragDenStaat hat eine große Datenbank von Behörden aus ganz Deutschland (https://fragdenstaat.de/behoerden/ und https://fragdenstaat.de/api/v1/), aber trotzdem fehlen manche Behördengruppen ganz oder sind unvollständig.
Einige Beispiele:
- [ ] Finanzämter
- [x] Verwaltungsgerichte
- [x] Kommunale Unternehmen (Details in https://github.com/okfde/fragdenstaat_de/issues/46)

**Comment by Unterstrichmoepunterstrich** [comment]
hey @arnese,

ich habe gerade diesen Fall und habe eine Antwort von dieser [https://www.thueringen.de/th3/polizei/landespolizeidirektion/index.aspx](Behördel) erhalten. Es handelt sich um die Thüringer Landespolizeidirektion. E-Mailadresse müsste diese sein:  poststelle.lpd@polizei.thueringen.de und die Anschrift Andreasstraße 38 in 99084 Erfurt.

Bitte mal einflegen, da ich sonst die Antwort nicht hochladen kann.

**Comment by arnese** [comment]
Moin @Unterstrichmoepunterstrich, bitte hier eintragen: https://fragdenstaat.de/behoerden/vorschlagen/
