### ISSUE TITLE
Batch-Anfrage an **alle** Ministerin in DE Feedback

### ISSUE THREAD

**Issue by jfilter** [okfde/fragdenstaat_de#118]
- Behörden in Sachsen wurden angeschrieben, obwohl ich keine Anfrage nach UIG gestellt habe. Vielleicht sollte man das gesondert bearbeiten?
- Behörden in NRW wollen alle meine Adresse
- Behörden in MV weigern sich (das übliche)

**Comment by arnese** [comment]
Sachsen: Passt, denke ich. Können ja freiwillig was rausgeben. Gab es noch weiteres Feedback?

**Comment by jfilter** [comment]
Nee, passt, gab jetzt nicht Weltbewegendes.
