### ISSUE TITLE
Sparkasse Schwerin: Contradictory search results

### ISSUE THREAD

**Issue by johnjohndoe** [okfde/fragdenstaat_de#119]
The website states that there is one IFG request when I search for `sparkasse schwerin` as shown in the screenshot below:

![sparkasse-schwerin1](https://user-images.githubusercontent.com/144518/42278712-047acf88-7f9c-11e8-9fb0-0db66e3d4443.png)

However, when I want to see that request the website claims that there is no request as shown in below screenshot:

![sparkasse-schwerin2](https://user-images.githubusercontent.com/144518/42278772-22f12246-7f9c-11e8-8ef6-95df40579314.png)

**Comment by arnese** [comment]
True. There is one non-public request which is shown in the list, but obviously can't be shown itself. We have to work on the display.

**Comment by jfilter** [comment]
now public: https://fragdenstaat.de/anfrage/sponsoring-wirtschaftsball-2018/

**Comment by arnese** [comment]
This is actually an older problem: https://github.com/okfde/froide/issues/125
