### ISSUE TITLE
Provide an RSS Feed for the Blog

### ISSUE THREAD

**Issue by tordans** [okfde/fragdenstaat_de#120]
The blog https://fragdenstaat.de/blog/ doesn't have an RSS Feed.
It would be awesome if it did.

```
<link rel="alternate" type="application/rss+xml" 
  title="FragDenStaat Blog" 
  href="/blog.rss" />
```

**Comment by arnese** [comment]
It does, but we should link to it properly: https://fragdenstaat.de/blog/feed/

**Comment by stefanw** [comment]
link tag is now present.
