### ISSUE TITLE
Interface zum Melden geänderter Behördendaten

### ISSUE THREAD

**Issue by roikiermedia** [okfde/fragdenstaat_de#122]
Ein Formular um auf geänderte Daten einer Behörde hinzuweisen wäre praktisch. Eine Mailadresse dafür in den FAQs würde es wahrscheinlich auch tun.   
Beispiel: Die Fachhochschule Flensburg hat ihren Namen, Domains, etc geändert zu Hochschule Flensburg. Hier könnte der User auf der Behördenseite einen "Änderungen vorschlagen"-Button auswählen um hierauf aufmerksam zu machen.

**Comment by arnese** [comment]
Das ist jetzt auf jeder Behördenseite möglich.
