### ISSUE TITLE
add mastodon icon

### ISSUE THREAD

**Issue by jfilter** [okfde/fragdenstaat_de#126]
https://chaos.social/web/statuses/101359234792905641

**Comment by arnese** [comment]
Icon: https://fontawesome.com/icons/mastodon?style=brands

**Comment by stefanw** [comment]
We are currently using Font Awesome 4 which does not include the mastodon icon.

**Comment by arnese** [comment]
I don't see us implementing this as we don't have the capacity to actively use Mastodon.

**Comment by jfilter** [comment]
To be honest: I think it's fine to use the mastodon account only during congress / chaos events.
