### ISSUE TITLE
Straßenverkehrsrechtliche Dokumente

### ISSUE THREAD

**Issue by tessarakt** [okfde/fragdenstaat_de#128]
Es wäre interessant, straßenverkehrsrechtliche Anordnungen und Verkehrsschau-Protokolle so mit Geodaten annotieren zu können, dass sie man sie auf einer Karte direkt finden kann (ggf. runtergebrochen bis auf einzelne Verkehrszeichen). Die Behörden haben da leider selbst oft keine vernünftige Systematik oder Datenbank, geschweige denn eine einheitliche.

Ziel könnte langfristig der Aufbau eines Verkehrszeichen-Katasters sein.

Solche Daten wären sehr interessant für Aktivisten im Bereich der Verkehrspolitik.

**Comment by arnese** [comment]
Okay. Hast du denn schon welche angefragt? Kannst du gerne ausprobieren.
