### ISSUE TITLE
Terminkalender von Politikern und Führungskräften in Behörden

### ISSUE THREAD

**Issue by tessarakt** [okfde/fragdenstaat_de#130]
Man kann ja die externen Termine in den Kalendern dieser Leute per IFG erfragen. Diese Daten sollten dann sinnvoll mit Organigrammen und mit den Gesprächsprotokollen zu diesen Terminen verknüpft sein. Die Gesprächsprotokolle sollte man direkt anfordern können, wenn man den Kalender (die Terminliste) hat.

**Comment by arnese** [comment]
"Diese Leute"? Du kannst natürlich versuchen, Kalender anzufragen. Das ist nicht immer ganz einfach, aber es gibt schon einige Vorbilder: https://fragdenstaat.de/anfragen/?q=terminkalender&status=&jurisdiction=&category=&publicbody=&tag=

**Comment by tessarakt** [comment]
Ja, "diese Leute" = kurz für Politiker und Führungskräfte, wie im Titel des Issues genannt. Das wichtigste wären die sinnvollen Verlinkungen und Metadaten.
