### ISSUE TITLE
Schwärzen mit Firefox funktioniert nicht

### ISSUE THREAD

**Issue by HappyPony** [okfde/fragdenstaat_de#133]
Schwärzen von PDF-Dateien mit Firefox funktioniert nicht. Getestet mit Firefox Version 65.0.1 (64-Bit). Ich habe die Antwort der Behörde hochgeaden. Das Schwärzen der PDF-Datei ist dann nur mit Microsoft Edge gelungen.

**Comment by arnese** [comment]
Müsste gehen.
