### ISSUE TITLE
Information not completely available

### ISSUE THREAD

**Issue by Ameinsenbaer** [okfde/fragdenstaat_de#135]
Add a Status "Information not completely available"

**Comment by jfilter** [comment]
How is it different from partially successful?

**Comment by Ameinsenbaer** [comment]
Partially successful is (so I think) most used when a requests became declined. But I think it's also a way to add a reason for partially successful, which says that the publicbody hadn't all requested information.

**Comment by Unterstrichmoepunterstrich** [comment]
> Partially successful is (so I think) most used when a requests became declined. 

My opinion is a little bit different. E.g. you are requesting  stuff, where third parties - like companies - are involved and can ensure that parts of the contract/document are censored.

**Comment by jfilter** [comment]
It depends on the amount of redaction, but for me it sounds like a successful request.

I don’t think that there is no clear definition for partially successfully. But if you received some information but not all, this sounds like partially successful to me.
