### ISSUE TITLE
Corrupt "Topf Secret" Requests

### ISSUE THREAD

**Issue by jfilter** [okfde/fragdenstaat_de#136]
There are some corrupts secrets that cause the mobile app to crash and also are not properly displayed on the web version. Looks like they were all added post hoc?

For instance this one: https://fragdenstaat.de/anfrage/kontrollbericht-restaurant-gusticus-raststatte-greding-west/

**Comment by stefanw** [comment]
Yes, they were added manually with  just basic info representing the offline made requests (don’t ask). What info is missing that causes the crash?

**Comment by jfilter** [comment]
`last_message` (I guess this causes the crash, didn't verify) and `due_date` are null.

**Comment by stefanw** [comment]
I filled in `last_message` for these requests. You are right that they should never be empty. However, `due_date` can reasonably be empty (e.g. request is in some court proceedings and there's no fixed due date anymore.)
