### ISSUE TITLE
Wrong wording for receiving postal responses

### ISSUE THREAD

**Issue by jfilter** [okfde/fragdenstaat_de#139]
I digitized a postal response but it's written that they send an email: https://fragdenstaat.de/anfrage/videofilm-demokratie-schutzen-verfassungsschutz/

![Screen Shot 2019-04-23 at 10 59 43](https://user-images.githubusercontent.com/3450307/56568348-12c79100-65b7-11e9-8178-c50861b217c1.png)

**Comment by stefanw** [comment]
Currently the event system does not store a reference to the message thus cannot infer the correct kind of message. The event system is mostly used to inform users about what happened in the last 24 hours when they follow a request.

Two solutions come to mind:

- remove public display of events -> they serve no real user purpose and are quite hidden anyway.
- Improve on the event to make them more usable and user friendly

**Comment by jfilter** [comment]
Or maybe simple change "E-Mail" to "Nachricht"?

**Comment by stefanw** [comment]
I like your thinking.

**Comment by jfilter** [comment]
😘
