### ISSUE TITLE
Erweitere Berliner Behörden

### ISSUE THREAD

**Issue by stefanw** [okfde/fragdenstaat_de#14]
Simon Weiß hat IFG-anfragbare Behörden angefragt:
http://pardok.parlament-berlin.de/starweb/adis/citat/VT/17/KlAnfr/ka17-12429.pdf

Muss mit der aktuellen Liste konsolidiert werden:
https://docs.google.com/spreadsheet/ccc?key=0AhDkodM9ozpddFV6Ylh0enNQU21GZWUzWUFaY3kwRHc#gid=0

**Comment by arnese** [comment]
ist erledigt, habs abgeglichen und teils hinzugefügt
