### ISSUE TITLE
Team-Projekte anlegen

### ISSUE THREAD

**Issue by cybertschunk** [okfde/fragdenstaat_de#142]
Hallo,
auf der Team-Seite gibt es eine Projekt-Übersicht. Soweit ich es überblickt habe, kann man jedoch nirgendwo Projekte anlegen. Ist das mein Fehler? Ansonsten wäre es spitze, sowas wie Projekte vollständig zu implementieren, da man darüber gebündelte Anfragen deutlich besser verwalten könnte.

**Comment by stefanw** [comment]
Projekte sind momentan Teil von [FragDenStaat Plus](https://fragdenstaat.de/plus/), dafür kannst du dich freischalten lassen.
