### ISSUE TITLE
PeerTube statt Vimeo

### ISSUE THREAD

**Issue by Grammost** [okfde/fragdenstaat_de#143]
### Problem

Die Videos auf FragDenStaat werden über die Plattform Vimeo geladen. Damit funkt der Besucher der Seite Server in den USA an und bekommt einen Drittanbieter-Cookie gespeichert.

### Lösung

Stattdessen auf PeerTube die Videos hosten. PeerTube baut auf dem gleichen Protokoll wie Mastodon auf (ActivityPub), ist unter AGPLv3 lizensiert und lässt sich somit dezentral/förderiert betreiben. PeerTube wird unter der Leitung der französischen Non-Profit Framasoft entwickelt.
Entweder FragDenStaat hostet selbst eine kleine Instanz (öffentlicher Login kann abgeschaltet werden) oder sucht sich eine bestehende Instanz raus. Bei dem letzteren wird man sich wahrscheinlich nicht sicher sein können, wie lange dieser die Domain besitzt und die Instanz betreibt. 
Einbetten lassen sich die Videos ganz einfach über einen iframe, den Einbettungscode bekommt man, wie bei Youtube, einfach per Rechtsklick.

Mehr Informationen zu PeerTube:
https://joinpeertube.org/de/

**Comment by arnese** [comment]
Wir hosten das Video jetzt direkt bei FragDenStaat.
