### ISSUE TITLE
Can't edit my blog article anymore

### ISSUE THREAD

**Issue by jfilter** [okfde/fragdenstaat_de#145]
1. <https://fragdenstaat.de/fds-admin/fds_blog/article/353/change/>
2. 'auf Website anzeigen'
3. https://fragdenstaat.de/blog/2019/04/01/manuela-schwesig-sektempfang-klage-landtag-mecklenburg-vorpommern/
4. results into 404.

It used to work but I changed the URL slug the last time. Did it break something?

**Comment by arnese** [comment]
add ?edit

**Comment by jfilter** [comment]
H4X0r

**Comment by stefanw** [comment]
Der „*Inhalt bearbeiten*“ hilft beim nächsten Mal auch.
