### ISSUE TITLE
Status: Zugangsgewährung auf andere Weise als beantragt

### ISSUE THREAD

**Issue by tessarakt** [okfde/fragdenstaat_de#146]
Folgende Verbesserungsvorschläge:
- Erfassen, welche Zugangsart beantragt wurde. Normalerweise (laut Template) ist dies Übersendung von (elektronischen) Dokumenten, das könnte also der Default sein.
- Ermöglichen zu erfassen, auf welche Art der Zugang gewährt wurde. Ich habe jetzt schon zweimal gehabt, dass die Behörde nur Akteneinsicht gewähren wollte.
- Ein Flag für den Status der Akteneinsicht. Bis der Antragsteller tatsächlich die Akteneinsicht gemacht hat, ist der Vorgang ja noch nicht so richtig fertig ... Man könnte auch sowas erfassen wie "Termin vereinbart".
- Interessant wäre dann eine Statistik dazu. Vielleicht kommt es ja nur mir so vor, aber IMO scheint es für Behörden sehr verlockend zu sein, diese Variante zu wählen - viele Antragsteller werden es dabei dann belassen und nie zur Akteneinsicht aufschlagen ...
- Keine Ahnung wie das rechtlich ist, aber vielleicht könnte man ja auch andere bevollmächtigen bzw. bei der Akteneinsicht vertreten. Ich komme so schnell nicht nach Berlin zum BMG, aber vielleicht braucht ja stattdessen jemand etwas aus Ulm ...

**Comment by jfilter** [comment]
Also neben "Kosten erhoben" ein Flag ob Akteneinsicht gefordert wurde. Finde ich gut. Ich würde dazu gerne noch aufnehmen, ob ein Brief per Einschreiben kam. Das ist mir schon zwei mal vorgekommen und ich empfinde es pure Schikane.

**Comment by stefanw** [comment]
Ich würde ungern eine Liste von ewig vielen Checkboxen (bzw. Datenbank-Flags) an die Anfrage oder an einzelne Nachrichten hängen.

Es gibt die Möglichkeit Anfragen mit Schlagworten zu versehen. Etwas ähnliches gibt es auch für Nachrichten, aber noch intern. Ggf. ließe sich das darüber lösen?

**Comment by arnese** [comment]
Dies scheint in der Praxis kaum ein Problem zu sein. Ich sehe, dass Leute in ihren "Post erhalten"-Mails dann schreiben, wie sie Infos erhalten haben.
