### ISSUE TITLE
Fax Unterschriften

### ISSUE THREAD

**Issue by basti-schr** [okfde/fragdenstaat_de#148]
Da nicht abschließend geklärt ist, ob Computerfaxe rechtsmäßig sind sollte man es nicht offensichtlich machen, dass die Unterschrift eingefügt ist. 
Die in der Datenbank hinterlegte Unterschrift kann für das erste Fax verwendet werden. Bei allen weiteren sollte eine neue Unterschrift abgefragt werden.
Dann ist auf jedem Fax der Anfrage eine andere Unterschrift.

**Comment by arnese** [comment]
Das werden wir erstmal nicht machen, weil es bisher keine Probleme gab.
