### ISSUE TITLE
EU-Gesetze zur Ablehnung fehlen

### ISSUE THREAD

**Issue by rugk** [okfde/fragdenstaat_de#149]
Wird eine Anfrage (teilweise) abgelehnt, kann man verschiedene Bundes/Landesgesetze Deutschlands als Grund auswählen.

Inzwischen kann man ja aber auch EU-Institutionen anfragen.
Diese Gesetzesauswahl geht aber nicht mit EU-Gesetzen.

**Comment by stefanw** [comment]
Ausnahmegründe für 1049/2001 wurden eingefügt.
