### ISSUE TITLE
Missing translation for pseudonym registrations sentence

### ISSUE THREAD

**Issue by rugk** [okfde/fragdenstaat_de#152]
> You may use a pseudonym if you don't need to receive postal messages.

on https://fragdenstaat.de/account/login/

![grafik](https://user-images.githubusercontent.com/11966684/67203220-de6c4a80-f40a-11e9-806e-73bdd6991104.png)

This is missing the German translation.

**Comment by ThodeC** [comment]
I can go for this (native speaker).
In which file is the string for this?

**Comment by stefanw** [comment]
It's in okfde/froide in the `locale/*/*/django.po` file. Fixed now.
