### ISSUE TITLE
DHL-Tracking Nachrichten filtern

### ISSUE THREAD

**Issue by intrigus** [okfde/fragdenstaat_de#153]
Die EU-Institutionen verschicken gerne Briefe via DHL-Express.
Dabei erhält der Anfragesteller eine Mail von DHL die einen Trackingcode enthält.
Zusätzlich enthält die Mail den Namen und die Adresse des Anfragestellers.
Alle drei Dinge enthalten private Informationen, die nicht öffentlich sein sollten.
Meiner Meinung nach sollten alle Trackingnachrichten von DHL und co gefiltert werden oder manuell veröffentlicht werden müssen.

**Comment by stefanw** [comment]
Der Inhalt von DHL-Nachrichten wird jetzt automatisch nur für den Antragstellenden angezeigt.
