### ISSUE TITLE
Phone numbers in der database

### ISSUE THREAD

**Issue by Unterstrichmoepunterstrich** [okfde/fragdenstaat_de#158]
Hello,

what do you think about using [DIN 5008](https://www.din-5008-richtlinien.de/startseite/telefonnummern/) for phone/fax numbers? inclusive a leading +49 and - as seperator.
Please gimme some feedback.

**Comment by stefanw** [comment]
When the validity and format becomes relevant during [our fax sending](https://github.com/okfde/froide-fax/), the [fax number is automatically processed](https://github.com/okfde/froide-fax/blob/master/froide_fax/utils.py#L15-L34) and stored in the [E.164 numbering format](https://en.wikipedia.org/wiki/E.164).

Only email and fax numbers are currently stored on their own. Other contact data is currently stored as free text.

Details of DIN norms are usually not freely available, so we try to stay away from DIN norms where possible for ideological reasons as well.
