### ISSUE TITLE
Same article on page 1 and page 2 on the blog

### ISSUE THREAD

**Issue by jfilter** [okfde/fragdenstaat_de#159]
The article about Hambacher Forst is on two pages.

Page 1
![Screen Shot 2019-12-16 at 14 13 58](https://user-images.githubusercontent.com/3450307/70909726-5ff8e700-200e-11ea-890d-cb27215f0345.png)

Page 2
![Screen Shot 2019-12-16 at 14 14 15](https://user-images.githubusercontent.com/3450307/70909749-68e9b880-200e-11ea-87b6-1d6303c1d82a.png)

**Comment by pajowu** [comment]
Fixed in #445
