### ISSUE TITLE
missing 'e' 

### ISSUE THREAD

**Issue by g0ldfisch** [okfde/fragdenstaat_de#16]
in the link for the mailinglist at the mainpage (at the bottom) misses an 'e'

**Comment by optikfluffel** [comment]
@g0ldfisch maybe you have configured your os (or browser) in english? At least [at a first glance it looks ok](https://github.com/okfde/fragdenstaat_de/search?utf8=✓&q=mailinglist%21).

**Comment by stefanw** [comment]
I'm closing this. You could use the Denglisch word "Malingliste" or the English Mailinglist in this case.
If they are strong opinions on this, please open a mergeable pull request instead. Thanks!
