### ISSUE TITLE
Behörde editieren

### ISSUE THREAD

**Issue by Ameinsenbaer** [okfde/fragdenstaat_de#162]
Da sich ab und an bei Behörden Informationen ändern können oder auch welche falsch eingegeben sein würde ich vorschlagen, dass auf der Übersichtsseite einer Behörde ein Knopf ergänzt wird, mit dem man einzelne Informationen der Übersicht ändern kann.

**Comment by arnese** [comment]
Issue bereits hier: https://github.com/okfde/fragdenstaat_de/issues/122
