### ISSUE TITLE
Duplicate Classifications

### ISSUE THREAD

**Issue by jfilter** [okfde/fragdenstaat_de#163]
![Screen Shot 2020-05-13 at 15 27 23](https://user-images.githubusercontent.com/3450307/81818660-9ccdf900-952e-11ea-9a3c-7a78c43c07dc.png)

**Comment by stefanw** [comment]
Fixed it! Gave you access to more permissions so you can fix it yourself next time.

**Comment by jfilter** [comment]
And 'fixing' means merging the classifications right? "Oberbehörde zuweisen"?

**Comment by stefanw** [comment]
that would move the classification to a different parent. I clicked on 'Behörden mit dieser Klassifikation', selected them all and gave them a new classification, then deleted the old one (which then has 0 connected public bodies).
