### ISSUE TITLE
Text-Footer-Schere

### ISSUE THREAD

**Issue by jfilter** [okfde/fragdenstaat_de#167]
![Screen Shot 2020-06-14 at 14 41 45](https://user-images.githubusercontent.com/3450307/84593633-6ea14900-ae4d-11ea-8f96-afa742567202.png)

Einsteiger-Guide ⇾ Einstiegs-Guide

Ansonsten z. B.:
Journalist:innen
Entwickler:innen

**Comment by arnese** [comment]
Danke für den Hinweis. https://github.com/okfde/fragdenstaat_de/commit/d11c9edcd7efbf279b8658b962dbb4d2c18bd91b
