### ISSUE TITLE
Falscher Link bei EU-Behörden

### ISSUE THREAD

**Issue by rugk** [okfde/fragdenstaat_de#169]
https://fragdenstaat.de/info/informationsfreiheit/europaeische-union/ verlinkt bei
> → Zu den EU-Behörden auf FragDenStaat

zu 
https://fragdenstaat.de/behoerden/?q=&jurisdiction=europa&category=

Es sollte aber (da Kategorie offenbar umbenannt) dazu verlinken:
https://fragdenstaat.de/behoerden/?q=&jurisdiction=europaeische-union&category=&classification=

Sonst zeigt es einfach ale Behörden.

**Comment by arnese** [comment]
Geändert.
