### ISSUE TITLE
Feature request - Sort search results by creation date

### ISSUE THREAD

**Issue by error401de** [okfde/fragdenstaat_de#174]
I'd appreciate very much if it would be possible to sort search results by the creation date (so the results of e.g. https://fragdenstaat.de/anfragen/?q=test&status=&jurisdiction=&campaign=&category=&publicbody=&tag=&user=)

In my case I check results for the city I'm living in from time to time. But it's hard to keep track if the results can't be properly sorted by the creation date.

Thanks for considering!

**Comment by arnese** [comment]
Thank you! I hope we can enhance the search next year. We have wanted this for a long time ... https://github.com/okfde/froide/issues/148
