### ISSUE TITLE
Issues Klima-Gebäude-Check

### ISSUE THREAD

**Issue by arnese** [okfde/fragdenstaat_de#176]
- [x] Besseres Filtern von amenities, die nicht öffentliche Gebäude sind: e.v",verein,sportplatz,club,gmbh,café,restaurant,pfarrzentrum

- [x] ermöglichen, die Behörde im Anfrageprozess zu ändern

- [x] Neu hinzufügen als Behörde: Schulen, Krankenhäuser, ...

- [x] Weitere Gemeinden hinzufügen: Ortsgemeinden Rheinland-Pfalz, Gemeinden Mecklenburg-Vorpommern, Gemeinden Niedersachsen, Gemeinden Schleswig-Holstein, Gemeinden und Kreise Bayern

- [x] Umgang mit Mails, die in CC an Antragsteller gehen

- [x] Erfolgreiche Anfragen anzeigen

- [x] Zugang zu Backend zu Anfragen an bestimmte Gruppen ermöglichen

**Comment by rugk** [comment]
The issue in the [title with the house number being part of the PLZ](https://forum.okfn.de/t/unsere-neue-kampagen-startet-macht-mit/989/11?u=rugk) is still not fixed:
Just tested again:
![grafik](https://user-images.githubusercontent.com/11966684/102370849-d764ac00-3fbd-11eb-8971-ea45f62039a3.png)

**Comment by arnese** [comment]
Dann mach doch bitte ein neues Issue, es war nicht Teil von diesem.
