### ISSUE TITLE
Fristenberechnung verbessern

### ISSUE THREAD

**Issue by stefanw** [okfde/fragdenstaat_de#19]
Fristenberechnung sollte regionale Feiertage und ggf. Brauchtumstage respektieren.

**Comment by arnese** [comment]
Da sich die Frist ohnehin nicht an Arbeitstagen ausrichtet, ist dies nicht nötig.

**Comment by arasabbasi** [comment]
Wie meinst du das? Ich kann damit leben, dass das Issue geschlossen wird aber was ist mit § 31 III VwVfG?

**Comment by arnese** [comment]
Hier geht es nur um die Frist von einem Monat nach Antragsstellung zur Beantwortung - die ist de facto nicht weiter von Belang außer bei Anzeige von Verspätung. Wichtig sind Fristen zu Widerspruch und zu möglicher Untätigkeitsklage - die werden aber derzeit nicht erfasst.

**Comment by arasabbasi** [comment]
Verstehe und gehe mit dir d'accord.
