### ISSUE TITLE
Allow TXT as a format to send

### ISSUE THREAD

**Issue by rugk** [okfde/fragdenstaat_de#197]
Currently upload formats are restricted:
>  Der eingescannte Brief muss entweder im PDF-, JPG- oder PNG-Format sein, wurde aber als text/plain erkannt!

(That it says "eingescannte Brief" is a different issue: https://github.com/okfde/froide/issues/349)

It would be good if you also allow TXT files. Long lists of text may be useful to send to an agency as an attachment instead of inline.

**Comment by getjack** [comment]
Hm i think that TXT files are hard to blacken if it contains sensitive information plus the feature of adding a signature or watermark is not supported as far as i know.

Can you give a more detailed example for a use case? I was thinking about adding a PR for this as it seems simple but there is no discussion about that feature so i thought let's start one :)

**Comment by stefanw** [comment]
I doubt that public authorities know how or want to deal with TXT files. They are going to open them in Word and it will look bad, maybe there will be encoding problems. We used to send all messages as TXT files to the mediating authority ("here is the correspondence in this request") and they asked us to send a PDF instead. They now get the messages as a PDF export.

I understand the simplicity of TXT, but here the recipient will likely print or use an electronic filing system that likely deals better with email messages and PDF. 

I don't think there's much wrong with inline text. On their end they can probably deal with it, on our end the new request page can collapse individual messages to keep some order on the page.

**Comment by rugk** [comment]
AFAIK it was a simple list of things I wanted to request/details given in a "per line" format, which I did not want to attach/write inline.

But seeing @stefanw's reply now, this seems totally reasonable. :smiley:
