### ISSUE TITLE
Greetings redaction pattern leaks gender

### ISSUE THREAD

**Issue by alehaa** [okfde/fragdenstaat_de#199]
After e71691192005897f0b7fcf74811fad976423a5bb has been deployed, the redaction pattern doesn't match the gender specific greeting "geehrte" or "geehrter" anymore, but redacts the name only. Instead of "Sehr [redacted]" you'll get "Sehr geehrter [redacted]" now.

**Comment by alehaa** [comment]
I think the pattern still needs some fixing, as the female greeting is not covered partially, now. "Sehr [geehrter Herr Meier]" is covered, "Sehr geehrte [Frau Müller]" is not.

**Comment by stefanw** [comment]
You are probably right. It's unfortunate as I find the "Sehr [redacted]" a bit unfriendly, but I don't have a better solution for now.

**Comment by robbi5** [comment]
I've seen partial word redaction in some answers, like "Sehr geehrt[er Herr Meier]", "Sehr geehrt[e Frau Müller]"

**Comment by stefanw** [comment]
The redaction system is tricky. Some parts assume that it only ever operates on whole words (it uses `difflib.SequenceMatcher`). For now I'm happy with an ugly working solution.
