### ISSUE TITLE
Dropdown banner breaks parts of page after ease-in animation

### ISSUE THREAD

**Issue by hobofan** [okfde/fragdenstaat_de#202]
After the dropdown-wrapper (currently for "Black Box EU") finishes it's ease-in animation, it receives a `sticky` attribute, which makes it appear behind every content on the page, and makes it impossible to click some buttons.

Occurs in both Firefox and Chrome on macOS with a viewport width of 1440.

I think removing this line would solve it:

https://github.com/okfde/fragdenstaat_de/blob/8a30aee6e7939575c76da6821b20e81ce695c81b/frontend/javascript/donation.ts#L102

Alternatively it could make sense to disable the ease-in animation, as the banner is already displayed on site load, and then removed and eased in again, which makes the whole page jump rapidly.

Happy to provide further information if necessary.

Example:
![image](https://user-images.githubusercontent.com/601283/107337334-7daec880-6aba-11eb-8216-9d270282dd8c.png)

**Comment by stefanw** [comment]
Thanks, it was basically just missing a background color. We made it non-sticky for now, to be less obtrusive.
