### ISSUE TITLE
Informationsfreiheitssatzung Augsburg

### ISSUE THREAD

**Issue by Debakel** [okfde/fragdenstaat_de#211]
Augsburg hat eine [städtische Informationsfreiheitssatzung](https://www.augsburg.de/buergerservice-rathaus/rathaus/stadtrecht/informationsfreiheitssatzung). Wär's möglich die Vorlage anzupassen, sodass in Anfragen darauf verwiesen wird?

**Comment by arnese** [comment]
Moin! Haben wir schon. War aber der Stadt Augsburg noch nicht zugeordnet. Ist jetzt geschehen: https://fragdenstaat.de/anfrage-stellen/an/stadtverwaltung-augsburg/ 
Oder gibt es noch eine andere Behörde, bei der du die Satzung vorausgewählt vermisst?

**Comment by Debakel** [comment]
Hi Arne, danke dir! Ich hab kurz geguckt, bei den anderen Behören scheints zu passen.
