### ISSUE TITLE
Add backlink verification for Mastodon

### ISSUE THREAD

**Issue by rugk** [okfde/fragdenstaat_de#218]
You can get a green tick in your Mastodon profile and thus verify it is an official account connected to the given website by putting a special backlink on your website and verifying that on Mastodon.

See https://docs.joinmastodon.org/user/profile/#verification

**Comment by krmax44** [comment]
FontAwesome 4 has no icon for Mastodon, so it can't be added to the footer like the the other social links. Upgrading to FA5 (which has the Mastodon logo in its icon set) requires manually updating many classes and brings visual changes. Alternatively, we could edit the [SVG logo](https://upload.wikimedia.org/wikipedia/commons/4/48/Mastodon_Logotype_%28Simple%29.svg) to fit in with the other links, until we upgrade FA4.

**Comment by rugk** [comment]
Oh yeah, [or you use the SVG from Font Awesome 5](https://fontawesome.com/v5.15/icons/mastodon?style=brands) without including the whole font, but I see the problem yes.

Alternatively, if you jsut want a backlink, you can of course put it anywhere on the site as a minor text note – it does not need to use the icon.

**Comment by krmax44** [comment]
Finally added it!
