### ISSUE TITLE
Bundesland Hessen

### ISSUE THREAD

**Issue by kirsey** [okfde/fragdenstaat_de#22]
*  Gesetzestext
*  Behördenliste
*  Design
*  Presse

Neben dem IFG gibt es oft ein UIG oder VIG. Hier soll herausgefunden werden, ob diese Gesetze bereits existieren oder wann Ihre Einführung geplant ist. Falls keine Einführung geplant ist, wer blockiert diese Gesetze die beispielsweise nach der Richtlinie 2003/4/EG des Europäischen Parlaments und des Rates vom 28. Januar 2003 über den Zugang der Öffentlichkeit zu Umweltinformationen (http://www.umweltbundesamt.at/fileadmin/site/daten/umweltinfo/rl_umweltinformation.pdf) erforderlich sind?

**Comment by arnese** [comment]
Noch nicht viel besser, aber im Format: https://docs.google.com/spreadsheets/d/1QyeIgtCEz8OX8hDl2CYBgS55IlJEMqGFaGRjUklTgdU/edit?usp=sharing

**Comment by arnese** [comment]
Behörden sind bei FragDenStaat.de eingefügt.
