### ISSUE TITLE
Möglichkeit Anhänge zu löschen

### ISSUE THREAD

**Issue by jakobjakobson13** [okfde/fragdenstaat_de#224]
Hallo,

ich habe beim Hochladen von eingescannter Briefpost versehentlich eine falsche Datei hochgeladen und würde diese daher gerne wieder löschen. Allerdings habe ich keine Möglichkeit gefunden, dies zu tun.
Könnte eine Löschmöglichkeit zukünftig implementiert werden?

Danke und Gruss

**Comment by arnese** [comment]
Innerhalb von 36 Stunden ist das über "Anhänge verwalten" bereits möglich. Danach bitte einen Problembericht über "Melden" schicken.
