### ISSUE TITLE
Modify summery

### ISSUE THREAD

**Issue by Unterstrichmoepunterstrich** [okfde/fragdenstaat_de#235]
Hello,

sometimes I write a summery after my request. How is it possible to modify it later e.g. some writing mistakes.

Also would be nice to have some flags, to publish the summery under a create commons licences or GNU FDL which can be used at wikipedia.

**Comment by stefanw** [comment]
The summary can be edited by clicking the little pen symbol next to the heading:
<img width="440" alt="Screenshot 2021-11-26 at 10 29 00" src="https://user-images.githubusercontent.com/78356/143558534-79e6748f-87c6-4d88-baa8-78be61bc02ff.png">

According to our [terms of service](https://fragdenstaat.de/nutzungsbedingungen/) all user contributed content is licensed under CC Zero, so can be used in Wikipedia.
