### ISSUE TITLE
Bundesland Baden-Württemberg

### ISSUE THREAD

**Issue by kirsey** [okfde/fragdenstaat_de#24]
*  Gesetzestext
*  Behördenliste
*  Design
*  Presse

Neben dem IFG gibt es oft ein UIG oder VIG. Hier soll herausgefunden werden, ob diese Gesetze bereits existieren oder wann Ihre Einführung geplant ist. Falls keine Einführung geplant ist, wer blockiert diese Gesetze die beispielsweise nach der Richtlinie 2003/4/EG des Europäischen Parlaments und des Rates vom 28. Januar 2003 über den Zugang der Öffentlichkeit zu Umweltinformationen (http://www.umweltbundesamt.at/fileadmin/site/daten/umweltinfo/rl_umweltinformation.pdf) erforderlich sind?

**Comment by arnese** [comment]
Hier sollten jetzt alle Behörden drin sein: https://docs.google.com/spreadsheets/d/1pTrGVTFjw7xTJjIR-p-JMzV4UyYZVHM5jostyg3juzQ/edit?usp=sharing

**Comment by arnese** [comment]
Behörden sind bei FragDenStaat.de eingefügt.
