### ISSUE TITLE
Button „suggest change“ without Action

### ISSUE THREAD

**Issue by fin** [okfde/fragdenstaat_de#240]
The Button „Änderung vorschlagen“ for Public Bodies does nothing when not logged in. I'd expect a tooltip or something similar to show up when clicked.

Example:
https://fragdenstaat.de/behoerde/45096/94-schule-oberschule-der-stadt-leipzig-leipzig-ot-grunau-nord/

Steps to reproduce:
* Open above url in new private window
* Click Button „Änderung vorschlagen“

PS: This may be a froide bug, but since it also exists on .de I decided to report here.

**Comment by stefanw** [comment]
Weird, there's a bootstrap tooltip on top for me. Can you see if you have any JS errors?

<img width="308" alt="Screenshot 2021-12-13 at 08 39 38" src="https://user-images.githubusercontent.com/78356/145779181-03760b90-001e-42d5-92bc-75252411d788.png">

**Comment by fin** [comment]
Weird indeed! It does work in Firefox, but does not in current Chrome/OSX, Safari 15.1/OSX and Safari 15.1/iOS. Neither Desktop browser shows any console errors.

**Comment by arnese** [comment]
Should be working now.
