### ISSUE TITLE
Fehlende Bundesbehörde: Ex-BAW -> DLZ-IT

### ISSUE THREAD

**Issue by Unterstrichmoepunterstrich** [okfde/fragdenstaat_de#26]
Die ehemalige BAW Dienststelle in Ilmenau wurde Anfang 2012 zur DLZ-IT ausgeliedert. Hervorgegangen ist die Bundesanstalt aus dem bei der Bundesanstalt für Wasserbau eingerichteten Dienstleistungszentrum Informationstechnik des Bundesministeriums für Verkehr, Bau- und Stadtentwicklung (DLZ-IT BMVBS). Anschrift ist die gleiche geblieben.

**Comment by arnese** [comment]
Danke! Hab ich eingetragen: https://fragdenstaat.de/behoerde/bundesanstalt-fur-it-dienstleistungen/

**Comment by Unterstrichmoepunterstrich** [comment]
@arnese  mir ist noch aufgefallen, dass bei der BAW immer noch Ilmenau als Außenstelle drin steht. Das kann raus

**Comment by arnese** [comment]
@Unterstrichmoepunterstrich alles klar, habs geändert, danke!
