### ISSUE TITLE
Feature Request: Zeit in der Fortschrittsanzeige des Koalitionstrackers

### ISSUE THREAD

**Issue by MaxMatti** [okfde/fragdenstaat_de#260]
Hi, vielen Dank für den Koalitionstracker! Es wäre aber super, in dem Balken sehen zu können wie viel der Zeit dieser Legislaturperiode bereits vergangen ist, um einen Vergleich zu haben.

zB so:
![image](https://user-images.githubusercontent.com/1584478/159887805-4eaa289b-b578-4271-8f97-524b36ef192d.png)

**Comment by hejjoe** [comment]
Ggf. sollte das Issue eher hier hin? https://github.com/okfde/froide-govplan/issues

**Comment by MaxMatti** [comment]
Ups ja sorry
