### ISSUE TITLE
Text für Vermittlung von Anfragen verbessern

### ISSUE THREAD

**Issue by arnese** [okfde/fragdenstaat_de#27]
Der Teaser-Text sollte neu lauten:
"Die Bundesbeauftragte für den Datenschutz und die Informationsfreiheit ist für die Vermittlung von Anträgen zuständig. Sie können hier um Vermittlung bitten. Bitte geben Sie auch einen Grund für die Vermittlung an."

Der Text in der Mail sollte den Vermittlungsgrund direkt sichtbar haben. Deswegen der neue Text:
"Sehr geehrte Damen und Herren,
ich bitte um Vermittlung bei einer Anfrage nach dem XXX. Die bisherige Korrespondenz finden Sie hier:
XXX
Ich bin der Meinung, die Anfrage wurde zu unrecht abgelehnt, weil …
Sie finden auch alle Dokumente zu dieser Anfrage als Anhang zu dieser E-Mail.
Sie dürfen meinen Namen gegenüber der Behörde nennen.
Mit freundlichen Grüßen"

**Comment by arasabbasi** [comment]
Kann man da nicht etwas allgemeineres formulieren?

"Ich bin der Meinung, meine Anfrage wurde zu unrecht in der erfolgten Form bearbeitet, weil..."

**Comment by arnese** [comment]
--Vermittlungstext ist prägnanter
