### ISSUE TITLE
Schwärzungen verbessern

### ISSUE THREAD

**Issue by Unterstrichmoepunterstrich** [okfde/fragdenstaat_de#28]
ich habe hier [1] eine Anfrag gestellt. 
interessanterweise steht in der AW vom 4.12. ein "Herr" da welches nicht zensiert wurde.
In der AW vom 10.12. wurde das "geehrter Herr" zensiert.

Falls da natürlich etwas geändert wurde, so hat sich das erledigt.

[1] https://fragdenstaat.de/anfrage/trainingszentrum-fur-die-russische-armee

**Comment by arasabbasi** [comment]
Wie wird eigentlich erkannt, was ein Name ist? 

Ich hab schon meine Anonymität aufgegeben, da mein Name wohl nicht durchs Raster passt :).

**Comment by arnese** [comment]
inzwischen gelöst
