### ISSUE TITLE
Anhang zur Antwort hinzufügen

### ISSUE THREAD

**Issue by kirsey** [okfde/fragdenstaat_de#29]
Ein tolles Feature wäre das Versenden von Anhängen. So könnten sich Nutzerinnen bei Ihrer Anfrage oder während der Kommunikation mit der Behörde leicht auf Dokumente berufen;-)

**Comment by Unterstrichmoepunterstrich** [comment]
es wäre zwar ein Feature, allerdings halte ich es Gründen für suboptimal z.B.:
* Darf der Anhang überhaupt veröffentlicht werden, Abmahnungen sind damit vorprogrammiert.
* E-Mail eignet sich nicht zum Verschicken Dokumenten. Ich kenne zwar nicht die E-Mailserver Einstellungen aller Ministerien, aber früher war so immer der Hinweis, alles über 5 MB nicht als Anhang zu verschicken.

**Comment by optikfluffel** [comment]
@Unterstrichmoepunterstrich das mit der Dateigröße könnte man ja einfach über Links lösen, die Abmahnproblematik allerdings nicht :unamused:

**Comment by arnese** [comment]
sending attachment will not be encouraged through fds in the near future.
