### ISSUE TITLE
None type in meta tag

### ISSUE THREAD

**Issue by riotbib** [okfde/fragdenstaat_de#320]
The meta tag of [Europol](https://fragdenstaat.de/behoerde/16042/europol/) at Google Search is including a None type.

> `<meta name="description" content="Europol ist ein(e) None in Europäische Union auf FragDenStaat"/>`

This seems to be a bug.
I do not know if this bug is recurring at other objects.

(Quite ironic though; thanks for your work!)

**Comment by stefanw** [comment]
Thanks! Classifications of public bodies can historically be empty. The description is kind of fixed now.
