### ISSUE TITLE
Donation via SEPA transfer via QR code

### ISSUE THREAD

**Issue by darkdragon-001** [okfde/fragdenstaat_de#326]
Can you please generate an [EPC QR-Code](https://en.wikipedia.org/wiki/EPC_QR_code) for donations via SEPA transfer for reduce the possibility of typing errors and speed up the donation process?

**Comment by stefanw** [comment]
AFAIK, this is only supported by Sparkasse and VR-Banken. We used to have a QR code (I think a different competing scheme!) but it was confusing to people who (if at all) are used to scan a QR code to open a website. And even people who are with these banks often do not know about the QR code or how to use it. I haven't seen it on any German donation page before either. So I'm skeptical if it will make thinks easier or rather more confusing.

I'd love to see an example where it's used as an explained optional way to go about a bank transfer.

**Comment by darkdragon-001** [comment]
The difference with my suggestion is that it is a standard by the European Payments Council. My bank (German FinTech "Vivid") supports it. It's a little bit a hen and egg problem: If there are no QR codes for invoices, banks don't implement it; if there are no banks supporting it, it's not included for invoices. I think the only way to change this is leading by example, implementing the standard and telling requesting implementation from other providers which one is using.

**Comment by arnese** [comment]
We decided against it after some user research.

**Comment by darkdragon-001** [comment]
@arnese could you elaborate on the problems you see with this suggestions? 

In the meantime, now _all_ of my banks support scanning the EPC QR code. This includes all of the major German banks.
