### ISSUE TITLE
Modifikationen Startseite

### ISSUE THREAD

**Issue by arnese** [okfde/fragdenstaat_de#34]
- [x] Neues OKF-Logo unten einbinden
- [ ] Text im Suchfeld oben rechts statt "Suchen" "Suchen nach Anfragen und Behörden"
- [ ] Möglichkeit, weitere Themen anstelle des Videos anzuzeigen, vgl. Slider von okfn.de 
- [x] "Was ist Informationsfreiheit?" ändern in "Was ist FragDenStaat?"
- [x] Unter dem Absatz zu FragDenStaat zwei Links: "Was ist Informationsfreiheit?" und "Wie stelle ich eine Anfrage?"
- [x] Kürzung der angezeigten Anfragen auf 6 Stück 
- [ ] Änderung der abgelehnten Anfragen in "Interessante Anfragen", Anzeige der letzten Anfragen der Woche
- [ ] Überschrift "Anfrage der Woche" ändern in "Blog" & mit Datum versehen
- [ ] Teaser von zwei vorherigen Blogeinträgen hinzufügen
- [x] Links "Blog" und "Behörden" aus Footer herausnehmen
- [ ] Feld: Letzte Kommentare?

**Comment by catcosmo** [comment]
- [ ] Suchfeld startseite Button blau
- [ ] Placeholder: z.B. Schule oder NSA
- [ ] 3 Schritt Anleitung mit weiterführendem link zu Hilfe (IFG INfo)
- [ ] Einleitungstext mit Aufruf und alignen
- [ ] Alle ansehen Button unter 6 Anfragen auf Startseite
- [ ] Blausituation
- [ ] Logo anpassen + alignen

**Comment by arnese** [comment]
- [ ] Spendenbutton oben (im Stil wie auf offenerhaushalt.de)
![buddha2](https://cloud.githubusercontent.com/assets/9381889/11609308/da7c5444-9b83-11e5-9d26-84be75656a8a.png)

**Comment by arnese** [comment]
migrated to #53
