### ISSUE TITLE
eine Zeitzone für die Mail-Nachrichten und https://fragdenstaat.de -Kommentare nutzen

### ISSUE THREAD

**Issue by HappyPony** [okfde/fragdenstaat_de#38]
ich rege an, **eine Zeitzone** für die Mail-Nachrichten und https://fragdenstaat.de -Kommentare zu nutzen. Momentan wird in den Mail-Nachrichten die _Koordinierte Weltzeit_ (UTC) [2] und in https://fragdenstaat.de -Kommentaren die _Mitteleuropäische Zeit (MEZ)_ [1] verwendet. Ich musste meine Kenntnisse zu Zonenzeiten [3] auffischen, um die Meldungen aus der Mail-Nachricht den https://fragdenstaat.de -Kommentaren zuzuordnen - s. [Bug-Meldung #165](https://github.com/stefanw/froide/issues/165) [4]. 

Ich nehme an, dass den Durchschnitts-fragdenstaat.de-User dieses Durcheinander aus der  _Koordinierten Weltzeit_ und der _Mitteleuropäischen Zeit_ durcheinander bringt.
1. Die Mitteleuropäische Zeit (MEZ) - https://de.wikipedia.org/wiki/Mitteleurop%C3%A4ische_Zeit
2. Koordinierte Weltzeit - https://de.wikipedia.org/wiki/Koordinierte_Weltzeit
3. Zonenzeit - https://de.wikipedia.org/wiki/Zonenzeit
4. Namen vertauscht - https://github.com/stefanw/froide/issues/165

**Comment by arnese** [comment]
Ist inzwischen behoben.
