### ISSUE TITLE
Möglichkeit den Antrag zurückzuziehen ohne dass man eine Antwort von der Behörde erhalten hat

### ISSUE THREAD

**Issue by arasabbasi** [okfde/fragdenstaat_de#39]
Man sollte die Möglichkeit besitzen den Vorgang abzuschließen, in dem man den Antrag zurückzieht. Derzeit kann man einen Vorgang nur abschließen, in dem man einen Brief der Behörde einstellt.

**Comment by akuckartz** [comment]
:+1:

**Comment by akuckartz** [comment]
Wurde bereits mit https://github.com/stefanw/froide/issues/24 gemeldet.

**Comment by arnese** [comment]
Wird hier geschlossen, weil bereits vorhanden
