### ISSUE TITLE
Bundesland Thüringen

### ISSUE THREAD

**Issue by stefanw** [okfde/fragdenstaat_de#4]
- [x] Behördenliste
- [x] Gesetzestext
- [x] Design
- [x] Presse

## Behördenliste

[Scraper](https://scraperwiki.com/scrapers/thuringen_public_bodies/) von [ThueringenWeb](http://www.thueringenweb.de/site/start) holt etwas zu viel ran. Echte Behörden schwer zu finden. Ggf. über Google Spreadsheet crowdsourcen.
Siehe auch: http://froide.readthedocs.org/en/latest/importpublicbodies/

## Gesetzestext

[Neues ThürIFG](http://www.parldok.thueringen.de/parldok/tcl/PDDocView.tcl?mode=get&LP=5&DokNum=4986&DokArt=Drs) muss gelesen und in einen Anfragetext umgewandelt werden.

## Design

CC-lizensiertes Panorama-Bild für Thüringen. [Flickr-Suche](https://secure.flickr.com/search/?q=Erfurt+Panorama&l=deriv&ss=1&ct=6&mt=all&w=all&adv=1)

## Presse

Angebot von Piraten Thüringen für PM.

**Comment by arasabbasi** [comment]
Hab vom Datenschutzbeauftragten einen Brief bekommen. Die 20 € sind gerechtfertigt. Aber man kann auf der Seite des Statistikamtes die Behörden kostenlos "gemeindeweise" kostenfrei abrufen.
Ich bin leider kurz angebunden. Kann den Brief aber gerne nachreichen...

**Comment by Unterstrichmoepunterstrich** [comment]
@arasabbasi 
sowas habe ich mir schon gedacht. Lässt du mir mal die Antwort zukommen, meine E-Mailadresse hast du ja (die soll nur nicht öffentlich hier auftachen).
Alternativ kannst du dich ja mal an dem XML-File versuchen, welches ich dir geschickt habe.

**Comment by arasabbasi** [comment]
Ich hab doch schon die xml in das froide Format umgewandelt? :)

VG aus Brüssel

----- Ursprüngliche Nachricht -----
Von: "Unterstrichmoepunterstrich" <notifications@github.com>
Gesendet: ‎01.‎01.‎2015 17:13
An: "okfde/fragdenstaat_de" <fragdenstaat_de@noreply.github.com>
Cc: "arasabbasi" <aras.abbasi@googlemail.com>
Betreff: Re: [fragdenstaat_de] Bundesland Thüringen (#4)

@arasabbasi 
sowas habe ich mir schon gedacht. Lässt du mir mal die Antwort zukommen, meine E-Mailadresse hast du ja (die soll nur nicht öffentlich hier auftachen).
Alternativ kannst du dich ja mal an dem XML-File versuchen, welches ich dir geschickt habe.

**Comment by Unterstrichmoepunterstrich** [comment]
@arasabbasi 
heißt das, dass fehlende Behörden/Kommunen darauf warten von @stefanw eingespielt zu werden bzw. du das ggf. tun kannst?

Grüße zurück…

**Comment by arasabbasi** [comment]
Ich hab deine xml zu dem froide csv Format umgewandelt. Jetzt muss man das in einem workshop anpassen, kategorisieren und so

Ich gehöre nicht zum Projekt. ;)

----- Ursprüngliche Nachricht -----
Von: "Unterstrichmoepunterstrich" <notifications@github.com>
Gesendet: ‎02.‎01.‎2015 23:20
An: "okfde/fragdenstaat_de" <fragdenstaat_de@noreply.github.com>
Cc: "arasabbasi" <aras.abbasi@googlemail.com>
Betreff: Re: [fragdenstaat_de] Bundesland Thüringen (#4)

@arasabbasi 
heißt das, dass fehlende Behörden/Kommunen darauf warten von @stefanw eingespielt zu werden bzw. du das ggf. tun kannst?
Grüße zurück…

**Comment by arnese** [comment]
Habe die Daten abgeglichen. Diese Gemeinden und Städte fehlen noch: https://docs.google.com/spreadsheets/d/1okA_dAdziIK3eL_YCOLZ11gSCYNRUUfRnqsdf5rT9Xc/edit#gid=0

**Comment by Unterstrichmoepunterstrich** [comment]
ich habe gleich angefangen zu vergleichen, da es ja zum 31.12.12 einige Gemeindefusionen/-änderungen gab und E-Mailadressen ggf veraltet sind. Anbei ein Teil von der Änderungen:

Stadt Königsee-Rottenbach stadt@koenigsee.de

Folgende Gemeinden waren vorher in einer VG und bilden nun eine eigenständige Landgemeinde:
Goldbach, Liebstedt, Mattstedt, Niederreißen, Niederroßla, Nirmsdorf, Oberreißen, Oßmannstedt, Pfiffelbach, Ulrichshalben, Wersdorf, Willerstedt

Gemeinde Ilmtal-Weinstraße OT Pfiffelbach Willerstedter Straße 1
99510 Ilmtal-Weinstraße

für Kromsdorf (+Ortsteil Denstedt), die letzte Gemeinde der ehemaligen VG Ilmtal Weinstraße, nimmt die neue Gemeinde eine erfüllende funktion wahr. 

Gemeinde Kromsdorf  Denstedt Weimarische Str.36b 99441 Kromsdorf gemeinde@kromsdorf-denstedt.de

mehr kommt später…

**Comment by arasabbasi** [comment]
Die sollen mal aufhören ihre Gemeinden neu zu organisieren xD

**Comment by arnese** [comment]
Danke, hab die Änderungen eingefügt! Kannst du auch selbst machen, da hat jeder Schreibberechtigung.

**Comment by Unterstrichmoepunterstrich** [comment]
Mit der neuen Landesregierung haben sich einige Ministerien im Name geändert und heißen entsprechend anders [1]. Leider finde ich nicht zu allen die neue E-Mailadresse.

[1] http://www.thueringer-allgemeine.de/web/zgt/suche/detail/-/specific/Felix-Der-TMBUWP-1842883773

Beim Suchen danach, fiel mir auf, dass einige noch gar nicht bei FdS hinterlegt sind (auch nicht in der alten Form, das Justizministerium fehlt z.B.)

alt; neu; E-Mail
Thüringer Innenminiserium; Thüringer Ministerium für Inneres und Kommunales; poststelle@tmik.thueringen.de
 Thüringer Ministerium für Wirtschaft, Arbeit und Technologie; Thüringer Ministerium für Wirtschaft, Wissenschaft und digitale Gesellschaft; ka
Thüringer Ministerium für Landwirtschaft, Forsten, Umwelt und Naturschutz; Thüringer Ministerium für Umwelt, Energie und Naturschutz; ka
 Thüringer Ministerium für Bau, Landesentwicklung und Verkehr; Thüringer Ministerium für Infrastruktur und Landwirtschaft; ka
Thüringer Ministerium für Soziales, Familie und Gesundheit; Thüringer Ministerium für Arbeit, Soziales, Gesundheit, Frauen und Familie; ka
Thüringer Ministerium für Bildung, Wissenschaft und Kultur; Thüringer Ministerium für Bildung, Jugend und Sport, ka
Thüringer Justizministerium; Thüringer Ministerium für Migration, Justiz und Verbraucherschutz; ka

**Comment by arnese** [comment]
Super, danke! Hab es alles geändert.

**Comment by Unterstrichmoepunterstrich** [comment]
meinen letzten Kommentar geupdated. gleich geblieben sind nur die E-Mailadressen Finanzministeriums (poststelle@tfm.thueringen.de) und der Thüringer Staatskanzlei (poststelle@tsk.thueringen.de)

**Comment by arnese** [comment]
merci!

**Comment by arasabbasi** [comment]
@arnese 
Was ist noch am Thüringer-Issue noch offen?

**Comment by arnese** [comment]
Behörden alle importiert
