### ISSUE TITLE
Antrag als PDF für Bundesländer mit Papierpflicht

### ISSUE THREAD

**Issue by kirsey** [okfde/fragdenstaat_de#40]
In Mecklenburg-Vorpommern sind die Behörden leider nicht verpflichtet Anträge zu bearbeiten, welche Sie per Email empfangen haben. Deshalb muss der Antragssteller üblicherweise den Antrag ausdrucken und postalisch einsenden. Es wäre eine große Erleichterung, wenn man den ausgefüllten Antrag als pdf-Dokument herunterladen könnte, um sich das ganze Kopieren und Formatieren zu ersparen.

**Comment by Unterstrichmoepunterstrich** [comment]
Ich habe das Landes-IFG gelesen. Geht denn nicht mal Fax?

**Comment by kirsey** [comment]
Da habe ich noch nicht drüber nachgedacht. Der Landesbeauftragte für Datenschutz und Informationsfreiheit MV sagt: "Eine Antragstellung per Fax oder E-Mail (mit qualifizierter elektronischer Signatur, § 3a VwVfG M-V) genügt nur dann der Schriftform, wenn die Behörde einen entsprechenden  Zugang  eröffnet  hat. Antragstellung zur  Niederschrift  bedeutet,  dass  ein  mündlich  (nicht  telefonisch)  gestellter  Antrag  von  einem Bediensteten  der  Behörde  wörtlich  aufgenommen  wird.  Diese  Formerfordernisse   gelten   auch   für   spätere   Konkretisierungen 
des   Informationsbegehrens." Es ist also nicht so einfach mit E-Mails in MV, doch sollte man faxen mal ausprobieren. 
Letztendlich müssen die Anträge jedoch unterschrieben werden... Ich bin mir nicht sicher, ob der Antragsteller persönlich unterschreiben muss oder eine Unterschrift der Form "im Auftrag" (i. A.) genügen sollte.

**Comment by arnese** [comment]
Ja, da ist Meck-Pomm tatäschlich speziell. Manche Behörden geben auch so Auskunft, aber oft auch nicht.
An welchem Punkt müsste denn dann eine PDF generiert werden? Vor dem Stellen der Anfrage, quasi als Alternative zum Abschicken der E-Mail, oder nach dem Abschicken des elektronischen Antrags?

**Comment by kirsey** [comment]
Ich tendiere dazu, den Antrag doppelt zu versenden.
Ich habe bereits Erfahrungen mit www.simple-fax.de gesammelt. Dort sendet man ein pdf-Dokument als Anhang an die E-Mailadresse: "Faxnummer@simple-fax.de", wobei "Faxnummer" die Zahlen der richtigen Faxnummer sind. Die Kosten liegen pro Fax bei 7 Cent. Vielleicht können wir den Antrag ja auch zusätzlich faxen?

**Comment by kirsey** [comment]
Es gibt auch kostenfreie Möglichkeiten (http://listoffreeware.com/list-of-best-free-online-fax-services-to-send-fax-free/), welche für den Anfang auch den Zweck erfüllen müssten.

**Comment by basti-schr** [comment]
Ich habe das selbe Problem tatsächlich gerade [hier](https://fragdenstaat.de/anfrage/kosten-des-neuen-hochschul-logos/) auch. Ist es möglich auch von Frag den Staat aus eine qualifizierte elektronische Signatur nach dem Signaturgesetz einzurichten und zu imlementieren?

**Comment by arnese** [comment]
Wenn es einen Fax-Anschluss gibt, könnte dieser auch für Widersprüche verwendet werden. Dann müsste es auch eine Unterschrift-Funktion mit der Maus geben.

**Comment by basti-schr** [comment]
Es wäre auch möglich einmalig die Unterschrift zu scannen und dann passend einfügen zu lassen.

**Comment by basti-schr** [comment]
Zu 2. kommt mir was mit TeX in den Sinn. Mann könnte da ein Modul bauen, das die Sachen entgegen nimmt und dann in ein PDF kompiliert.

**Comment by stefanw** [comment]
Für PDF-Generierung mit TeX hat @corny schon mal was gebaut: https://gist.github.com/corny/09cc32ce16d71838cb2373ea87fbae5a

Vielleicht kann @corny auch was zu Unterschriften im Browser sagen.

**Comment by corny** [comment]
Die Javascript-Bibliothek, die wir bei [Selbstauskunft.net](https://selbstauskunft.net/) einsetzen, haben wir als Open Source veröffentlicht:
https://github.com/digineo/signat0r

Ein Fax-Gateway mit Sendeberichten könnte ich bereitstellen, vielleicht sogar kostenfrei.

**Comment by Unterstrichmoepunterstrich** [comment]
> Anträge per De-Mail benötigen keine Unterschrift und das die De-Mail aktuell und wahrscheinlich für immer kostenlos sein wird, halte ich dies für eine gute Lösung.

Das mag vielleicht so sein, jedoch sehe nicht nur ich das Konzept hinter De-Mail mit großen Bauchschmerzen. Von daher würde ich nicht noch für eine weitere Verbreitung/Nutzung sorgen.

**Comment by jfilter** [comment]
Hallo und danke für deinen Kommentar. 

1. Ich denke nicht dass FdS Informationen rund um das IFG gezielt zurückhalten sollte. Man kann sagen, es geht auch per De-Mail, aber wir lehnen es aus folgenden Gründen ab / empfehlen die Verwendung nicht.

2. Nur was genau sind denn die nun Gründe?  Das es per default nicht verschlüsselt ist? Ist mir tendenziell für IFG-Anfragen egal. Die sind online einsehbar. ;)

3. Das ganze Projektmanagement war scheiße, ja. Nur ist mir persönlich für die Frage ob ich es nutze oder nicht egal. 

4. Da werden vielleicht 20 Anfragen per Jahr in MV gestellt. Das wird garantiert nichts an der Verbreitung ändern.

5. Was tatsächlich scheisse ist, ist der Umstand das private Firmen die Kommunikation mit dem Staat übernehmen. Der Staat sollte selbst eine Möglichkeit bieten mit ihm kostenfrei zu kommunizieren. Ich sehe nur gerade überhaupt keine politische Mehrheiten für so eine Forderung. Wir können ja eine netzpolitische Partei gründen, die sich für solche Sachen einsetzt. :D

Ich freue mich auf deine Antwort.
LG Johannes

**Comment by jfilter** [comment]
De-Email vs E-Post ist ein eigenes Thema: <https://www.heise.de/newsticker/meldung/E-Post-vs-De-Mail-Deutsche-Post-steigt-endgueltig-bei-De-Mail-aus-1840900.html>

Aber es kommt ja vielleicht die Fax-Übermittelung und damit wäre fds für die Zukunft gut gerüstet. 📠

**Comment by GiantCrocodile** [comment]
Ich meinte ja E-Post für Fax-Zwecke ;).

**Comment by arnese** [comment]
Inzwischen ist es möglich, in MV Faxe zu versenden - und Anfragen können als PDF runtergeladen werden.
