### ISSUE TITLE
UIG only

### ISSUE THREAD

**Issue by josaur** [okfde/fragdenstaat_de#409]
Durch den weiten Anwendungsbereich des UIG, auch auf Organisationen die nicht vom IFG oder Landesinformationsfreiheitsgesetzen erfasst sind, ergeben sich Institutionen bei denen ausschließlich Umweltinformationen angefragt werden können. Ich finde es daher sinnvoll dies zum einen kenntlich und zum anderen filterbar zu machen. Der Filter ist va. in dem Punkt wichtig wenn Informationen angefragt werden, die nicht vom UIG erfasst und daher UIG-only Institutionen nicht angezeigt werden sollen.

**Comment by arnese** [comment]
Hey, danke für den Vorschlag! Ich kann das nachvollziehen, aber habe den Eindruck, dass es nicht ganz zum bisherigen System passt: Wir haben Behörden in der Regel dann in der Datenbank, wenn wir finden, dass sie auskunftspflichtig sein müssten - also ggf. auch dann, wenn sie es gar nicht sind. Wir finden, dass alle Behörden nach dem IFG auskunftspflichtig sein sollten. Sie dann also rauszufiltern, passt nicht so ganz ...

**Comment by josaur** [comment]
Alles klar danke für die Erklärung. Das war mir tatsächlich nicht so ganz bewusst, dass die Datenbank mehr einen SOLL als einen IST Zustand abbilden soll, erklärt aber auch so manche Einträge zu informationspflichtigen Stellen. Closed
