### ISSUE TITLE
Überarbeitung der Antragsformulare für IFG 

### ISSUE THREAD

**Issue by kirsey** [okfde/fragdenstaat_de#41]
Hallo :-)
da die Behörden in der Regel nicht elektronisch antworten, habe ich hier einen Vorschlag wie wir unseren Wunsch der papierlosen IFG-Anfrage noch verstärken können. 

Alter Absatz:
Ich bitte Sie um eine Antwort in elektronischer Form (E-Mail) gemäß § 8 EGovG. Eine Antwort an meine persönliche E-Mail-Adresse bei meinem Telekommunikationsanbieter FragDenStaat.de stellt keine öffentliche Bekanntgabe des Verwaltungsaktes nach § 41 VwVfG dar.

Neuer Absatz:
Ich bitte Sie meine Anfrage elektronisch zu beantworten und mache hiermit von meinem Wahlrecht gem. Par. 7 Abs. 3 Satz 1 IFG i.V.m. Par. 8 EGovG gebraucht. Die Adresse wird daher nur vorsorglich mitgeteilt. Sollte von meiner Wahl abgewichen werden, bedarf dies einer gesonderten Begründung.
 Eine Antwort an meine persönliche E-Mail-Adresse bei meinem Telekommunikationsanbieter FragDenStaat.de stellt keine öffentliche Bekanntgabe des Verwaltungsaktes nach § 41 VwVfG dar.

**Comment by kirsey** [comment]
Weiterhin empfehle ich das Einfügen eines Absatzes zum Drittbeteiligungsverfahren(§ 7 Abs. 2, § 8 IFG).
Beispielsweise könnte dieser lauten:
Es liegen nach diesseitiger Sichtweise keine Gründe für ein Drittbeteiligungsverfahren (§ 7 Abs. 2, § 8 IFG) vor.

**Comment by arnese** [comment]
Moin!
Die Begründung zum Wahlrecht ist in letzter Zeit häufiger verwendet worden, ist jedoch juristisch bisher, soweit ich weiß, nicht hilfreich gewesen. Laut Datenschutzbeauftragten beinhaltet das Wahlrecht nur die Art der Antwort (also z.B.: schriftlich), nicht jedoch die Form (also: elektronisch, per Post etc.)
Welchen Nutzen hat der Absatz zum Drittbeteiligungsverfahren?

**Comment by kirsey** [comment]
Im IFG steht: "Auskünfte können mündlich, schriftlich oder elektronisch erteilt werden." 
und das Wahlrecht erlaubt die Auswahl zwischen diesen drei Möglichkeiten und bestimmt letztendlich auch die Form. 
Mit dem Drittbeteiligungsverfahren ist es wie mit der Aussage, dass es sich um eine "einfache Auskunft" handelt. Es kann nicht schaden und beschleunigt das Verfahren, falls die Behörde dieser Auffassung folgt.

**Comment by arnese** [comment]
Die BfDI schreibt dazu standardmäßig:
"Wie die Bundestagsverwaltung zu Recht ausführt, besteht ein Wahlrecht auf die Form der Auskunftserteilung nicht. Der § 1 Abs. 2 Satz 2 IFG sieht für die Art des Informationszugangs ein ausdrückliches Wahlrecht vor, so dass der Antragsteller/die Antragstellerin grundsätzlich selbst bestimmen kann, ob er/sie eine Auskunft erhalten, Akteneinsicht nehmen oder Informationen in sonstiger Weise zur Verfügung ge-stellt bekommen möchte. Von diesem Wahlrecht haben Sie Gebrauch gemacht, indem Sie in Ihrer Anfrage um eine Auskunftserteilung gebeten haben. Von der Art des Informationszugangs ist jedoch die Form des Informationszugangs zu unterscheiden.

Der § 7 Abs. 3 Satz 1 IFG sieht für die Auskunftserteilung die Möglichkeiten der mündlichen, schriftlichen oder elektronischen Erteilung vor. Anders als im Falle der Art des Informationszugangs, besteht bei der Form der Zugangsgewährung letztlich kein echtes Wahlrecht des Antragstellers/der Antragstellerin. Hier liegt die Entscheidung im Ermessen der Behörde. Zwar soll die Behörde bei der Ermessensausübung einen geäußerten Wunsch nach der Form berücksichtigen, jedoch ist sie hieran nicht gebunden. Insbesondere nur teilweise oder gar nicht erfolgreiche Anfragen, sind durch einen Bescheid, der mit einer Rechtsbehelfsbelehrung zu versehen ist, zu beantworten. Hierfür bedarf es allerdings nach den verwaltungsverfahrensrechtlichen Vorschriften einer ordnungsgemäßen Bekanntgabe, so dass in diesen Fällen zwingend eine Beantwortung in Papierform oder auf elektronischem Weg mittels einer qualifizierten elektronischen Signatur vorgeschrieben ist."

Das muss nicht heißen, dass diese Auffassung in jedem Fall richtig ist - aber Rückendeckung der BfDI gibt es hier nicht. 
Drittbeteiligungsverfahren schaue ich mir nochmal an, danke!

**Comment by kirsey** [comment]
Sicherlich ist das Wahlrecht bei der Form nicht ganz so groß wie bei der Art, aber grundsätzlich soll der Wunsch des Antragsstellers berücksichtigt werden :-)
Die Rechtsbehelfsbelehrung wird gerne verwendet um die Papierform zu begründen, jedoch gilt die Dreitagesfiktion für elektronische und postalische Zustellung gleichermaßen. Die Papierform ist somit nur bei förmlicher Zustellung (Einschreiben usw.) erforderlich, aber nicht bei einfacher Bekanntgabe.

**Comment by arnese** [comment]
Formulierungsmöglichkeit zum Verzicht auf Drittbeteiligung:
"Der Schwärzung personenbezogener Informationen Dritter gern . § 7 Abs. 2 Satz 2 IFG wird zugestimmt. Eine Begründung gern. § 7 Abs. 1 Satz 3 IFG und die Beteiligung Dritter gern. § 8 IFG sind daher nicht erforderlich."

Dies sollte optional sein und ggf. anklickbar beim Antrag.

**Comment by arnese** [comment]
Für personenbezogene Informationen eventuell:
"Soweit personenbezogene Informationen gern. § 5 Abs. 1 IFG betroffen sind, regen wir an, die Einwilligung der betroffenen Personen zunächst einzuholen. Sollte die Einwilligung wider Erwarten versagt werden, so gilt folgendes: Es überwiegt mit Blick auf den Zweck des Gesetzes, die demokratische Meinungs- und Willensbildung zu stärken und die Kontrolle staatlichen Handeins zu verbessern (vgl. BT -Drs. 15/4493, S. 6), das Informationsinteresse der Antragstellerin. Dies umso mehr, als die beantragten Informationen nicht der privaten Lebensgestaltung zuzuordnen sind. Überdies konnten dritte Personen nicht darauf vertrauen, dass ein Kontakt mit dem Bundeskanzleramt, welches dem IFG unterliegt, nicht an die Öffentlichkeit gelangen würde."
