### ISSUE TITLE
Design weitere Seiten

### ISSUE THREAD

**Issue by catcosmo** [okfde/fragdenstaat_de#44]
Alle Anfragen:
- [ ] Sortierung nach Status oben, dann Zuständigkeit, dann Kategorien
- [ ] Anfragenanzahl nach links unter Überschrift

Einzelne Anfrage:
- [ ] Status-Icon dazu
- [ ] Social Media-Buttons bei "Anfrage teilen"
- [ ] Infos-Button bei Interessierte
- [ ] Ecken abrunden

Behörden-Seite:
- [ ] Status-Icon in Übersicht

**Comment by arnese** [comment]
Startseite: "Fragen Sie Behörden in Deutschland nach Dokumenten!
FragDenStaat hilft Ihnen, Ihr Recht auf Informationen wahrzunehmen."

**Comment by arnese** [comment]
migrated to #57
