### ISSUE TITLE
Kommunale Unternehmen

### ISSUE THREAD

**Issue by kirsey** [okfde/fragdenstaat_de#46]
Bisher haben wir bei FragdenStaat fast ausschließlich Behörden befragt und den riesigen Bereich der kommunalen Unternehmen nicht berücksichtigt. Eine Einführung zu Fragestellugen der kommunalen Unternehmen findet sich hier: https://www.transparency.de/fileadmin/pdfs/Themen/Verwaltung/Kommunale_Beteiligungen.pdf
Es gibt auch erste Gerichtsurteile in diese Richtung: https://www.datenschutz.rlp.de/infofreiheit/de/gerichtsentscheidungen.php?submenu=land
Ein erster, wichtiger Schritt wird es sein die Adressdaten dieser Unternehmen zu beschaffen. Eine größere Datensammlung von über 1400 Unternehmen gibt es hier: http://www.vku.de/index.php?eID=tx_nawsecuredl&u=0&g=0&t=1454546668&hash=a1e98329e170ffb2a06b4a9739bf22a4c7fd7d45&file=fileadmin/media/Dokumente/VKU/Mitgliederbetreuung/15-12-17_Mitgliederstand_01.01.2016.pdf und hier: http://www.diekommunalenunternehmen.de/Vor-Ort,local.dku

Leider enthält die zweite Datenbank nur bei 30 der 1400 Unternehmen Informationen wie E-Mailadressen, Telefon- und Faxnummern. Hat jemand von euch eine Idee wie wir die fehlenden Informationen beschaffen können?

Meine Idee wäre ein Crawler, welcher die einzelnen Unternehmen bei google sucht und aus den Suchergebnissen die Daten extrahiert. Hat das schon mal jemand von euch gemacht bzw. Lust dazu?

**Comment by akuckartz** [comment]
:+1: für dieses Vorhaben.

**Comment by Unterstrichmoepunterstrich** [comment]
Was für mich aus der Tabelle nicht zwingend sichtbar wird, ob die genannten Unternehmen auch verwaltende Aufgaben für den Kreis/Stadt/Landnehmen. Bei der Lokalenwohnungsbaugenossenschaft hier ist dies z.B. nicht der Fall (diese ist allerdings nicht in der Liste enthalten…)

**Comment by kirsey** [comment]
Ich vermute mal du spielst auf den Anwendungsbereich der IFG's an:
"Einer Behörde im Sinne dieser Vorschrift steht eine natürliche oder juristische  Person  des  Privatrechts  gleich,  soweit sie  Aufgaben  der öffentlichen  Verwaltung  wahrnimmt  oder  dieser  Person  die  Erfüllung öffentlicher   Aufgaben  übertragen  wurde  oder  an  denen  eine  oder mehrere  der  in  Absatz  1  genannten  juristischen  Personen  des  öffentlichen  Rechts  mit  einer  Mehrheit  der  Anteile  oder  Stimmen  beteiligt sind."

Somit kannst du bei deiner Wohnungsbaugenossenschaft IFG's stellen, sobald deine Kommune mehr als 50% der Anteile besizt. Woher hast du die Information, dass du dich auf verwaltende Aufgaben in deiner IFG beschränken musst. 

Hier ist ein Beispiel, bei welchem die Gehaltsempfehlungen der Sparkassen erfolgreich beantragt wurden:http://www.juraforum.de/urteile/vg-duesseldorf/vg-duesseldorf-urteil-vom-23-11-2012-az-26-k-1846-12

Die Sparkassen habe ich übrigens bereits gescrapt und hoffe, dass sie bald online sind :-)

**Comment by Unterstrichmoepunterstrich** [comment]
> Somit kannst du bei deiner Wohnungsbaugenossenschaft IFG's stellen, sobald deine Kommune mehr als 
> 50% der Anteile besizt. Woher hast du die Information, dass du dich auf verwaltende Aufgaben in deiner IFG > beschränken musst?

hatte ich gemacht und die haben mir das mit Hinweis verweigert. Habe dann den TLFDI kontaktiert, der dem so zugestimmt hatte…

**Comment by kirsey** [comment]
Für das Thüringer IFG gilt:
Dieses Gesetz gilt für Behörden, Einrichtungen und sonstige öffentliche Stellen des Landes, der Gemeinden und Gemeindeverbände sowie für die sonstigen der Aufsicht des Landes unterstehenden juristischen Personen des öffentlichen Rechts und deren Vereinigungen, soweit sie in öffentlich-rechtlicher oder privatrechtlicher Form öffentlich-rechtliche Verwaltungsaufgaben wahrnehmen.

Ja, in Thüringen klingt das mit den Verwaltungsaufgaben einschränkend. Letztlich ist der Begriff der Verwaltung aber recht weit gefasst(https://de.wikipedia.org/wiki/Verwaltung#.C3.96ffentliche_Verwaltung), weshalb ich keinen Grund sehe warum jegliche IFG's scheitern sollten. Beispielsweise würde ich das Sponsoring durch die Wohnungsbaugenossenschaft als Verwaltungsaufgabe beschreiben.

**Comment by kirsey** [comment]
Leider ist die Liste der kommunalen Unternehmen sehr gemischt und letzendlich nur bruchteilhaft verwendbar. Ich denke eine große Gruppe kommunaler Unternehmen sind die Stadtwerke und dafür findet sich hier eine geeignete Liste: http://www.energie-chronik.de/071202d.htm bzw. https://de.wikipedia.org/wiki/Liste_von_Stadt-_und_Gemeindewerken

**Comment by arnese** [comment]
Ich würde das hier gerne neu aufleben lassen. Gibt es eine Liste von kommunalen Unternehmen mit Mailadressen?

**Comment by arnese** [comment]
in https://github.com/okfde/fragdenstaat_de/issues/116
