### ISSUE TITLE
IFG Bayern

### ISSUE THREAD

**Issue by kirsey** [okfde/fragdenstaat_de#48]
Bayern hat zwar noch kein echtes IFG aber ein brauchbares E-Government-Gesetz (https://netzpolitik.org/2016/baden-wuerttemberg-hat-jetzt-etwas-mehr-informationsfreiheit-bayern-immer-noch-nicht/), welches bereits weitgehende Auskunftsrechte beibhaltet (https://www.verkuendung-bayern.de/gvbl/jahrgang:2015/heftnummer:17/seite:458). Bisher gibt es dort ja nur einige Kommunen mit Informationsfreiheitsrechten in ihrer Satzung. Ich denke, dass wir das E-Government-Gesetz als IFG-Ersatz verwenden sollten und eine entsprechende Anfragevorlage für Bayern erstellen können.

**Comment by arnese** [comment]
Durch das E-Government-Gesetz wurde das Datenschutzgesetz geändert, welches ein allgemeines Auskunftsrecht beinhaltet.
Anfragen müsste also auf Basis des Datenschutzgesetzes gestellt werden, wobei hier ein "berechtigtes Interesse" nachgewiesen werden muss. (siehe http://byds.juris.de/byds/009_1.1_DSG_BY_1993_Art36.html)
Ich bin mir nicht sicher, ob das wirklich sinnvoll ist.

**Comment by kirsey** [comment]
Die Begründung des Interesses ist auch aus meiner Sicht ein großer Nachteil des Datenschutzgesetzes gegenüber dem IFG. Ich denke, dass in Abwägung des Einzelfalls eine journalistische Absicht ein berechtigtes Interesse für fast alle Anfragen darstellt (https://www.bfdi.bund.de/bfdi_wiki/index.php/28_BDSG_Kommentar_Absatz_1_Teil_2). Negativ fallen mir auch die vielen Behörden auf, welche von der Auskunftspflicht befreit sind.
Aber letztendlich ermöglichen wir hiermit einem Sechstel der deutschen Bevölkerung mit praktisch keinem Aufwand in ihrem Bundesland soetwas wie 'IFG-Anfragen' zu stellen. Dies sollte doch ein starker Anreiz sein, insbesondere weil es bisher keine zehn erfolgreichen IFG-Anfragen in Bayern gab.
Erfreulicherweise verpflichtet das E-Government-Gesetz die Behörden zur elektronischen Antwort wovon bestimmt auch fragdenstaat profitieren wird.

**Comment by arnese** [comment]
Okay, Hinweis ist eingefügt. 
Das E-Government-Gesetz redet war von elektronischen Antwort, aber womöglich bedeutet das auch "qualifizierte elektronische Signatur" bzw. De-Mail. Das wäre dann keine Hilfe.
