### ISSUE TITLE
CallDenBundestag

### ISSUE THREAD

**Issue by kirsey** [okfde/fragdenstaat_de#49]
Kennt Ihr das Pi-Phone? Es animiert Leute dazu im Rahmen einer Kampagne ihre Abgeordneten anzurufen(http://demo.piphone.eu/campaign/call2/demo). Ich denke, dass dieses Mittel auch für 'FragDenBundestag' sehr sinnvoll ist. Transparenz ist ein leicht zu verstehendes Thema und fast jeder kann die Vorteile von Transparenz in der Politik argumentieren. Aus meiner Sicht ist es überfällig das Pi-Phone (https://github.com/LaQuadratureDuNet/piphone) auch in Deutschland zu nutzen. Die benötigten Telefonnummern, Bilder usw. lassen sich leicht scrapen und ich werde mich da demnächst dranmachen. Was haltet ihr davon?

**Comment by arnese** [comment]
Hat sich das jetzt im Rahmen von FragDenBundestag erledigt? Was bringt das konkret? Wo sollte es eingesetzt werden?

**Comment by kirsey** [comment]
Ja, für FragdenBundestag hat sich das Thema erfreulicherweise erledigt. 
Dieses Tool ist ein riesiges Hilfsmittel für politische Kampagnen, weil wir die Bürger und die Politiker in einen Dialog bringen und somit effektive Lobbyarbeit für Informationsfreiheit und Transparenz betreiben können. E-Mails oder Unterschriftensammlungen sind dagegen eher Monologe und bewirken vergleichsweise wenig beim Empfänger.
Die Einsatzmöglichkeiten des Pi-Phones sind vielfältig, so könnten wir in verschiedenen Landtagen für ein IFG werben oder das Thüringer Transparenzgesetz unterstützen.

**Comment by arnese** [comment]
Schönes Tool; passt jedoch nicht zu FragDenStaat, da die Plattform auf IFG-Anfragen optimiert ist und nicht als Kampagnenplattform.
