### ISSUE TITLE
Anfragen werden nicht angezeigt

### ISSUE THREAD

**Issue by jakobjakobson13** [okfde/fragdenstaat_de#492]
Hallo zusammen,

mir werden unter "Meine Anfragen" und "Anfragen entdecken" gar keine Anfragen mehr angezeigt, obwohl es definitiv welche geben sollte.
Direkte Verknüpfungen auf Anfragen scheinen aber noch zu funktionieren.

Grüsse
Jakob

**Comment by stefanw** [comment]
Unser Such-Server war kurzzeitig nicht verfügbar. Ist jetzt behoben.
