### ISSUE TITLE
FragDasBundeskabinett

### ISSUE THREAD

**Issue by kirsey** [okfde/fragdenstaat_de#50]
Das Bundeskabinett ist die mächtigste politische Instanz Deutschlands und erstaunlich intransparent. Beispielsweise sind bisher weder die Tagesordnungspunkte noch die Teilnehmer bekannt. Dies können wir mit diesem Urteil (https://cdn.netzpolitik.org/wp-upload/Urteil_2016-03-045-2.pdf) nun ändern. Ich schlage aus diesem Grund vor, dass neue Tool für die öffentlichkeitswirksame Offenlegung dieser Daten zu nutzen.

**Comment by arnese** [comment]
Das Urteil ist noch nicht rechtskräftig, daher noch keine Weiterverfolgung möglich.
