### ISSUE TITLE
devsetup.sh fails with current Python and Yarn

### ISSUE THREAD

**Issue by bikubi** [okfde/fragdenstaat_de#507]
So possibly deeper incompatibilities?  
After updating my system (Arch Linux) and (re-)running [devsetup.sh](https://github.com/okfde/fragdenstaat_de/blob/b265155e0481c7b106a0aa447e8194ee1eb8b859/devsetup.sh) I ran into errors and found workarounds:

- Python 3.12 is maybe [missing pip](https://stackoverflow.com/a/77364602/629238)? Related workarounds seemed to work for a minute.
    - workaround: downgraded to Python 3.10 via `pyenv` 
- Yarn 1.22.22 and/or node 22.2.0 fail random tasks (e.g. node_modules…exif…yarn install) with a weird "/bin/sh bad interpreter, text file busy" error, at a temporary wrapper script like `/tmp/yarn--1716461794779-0.007020274052261355/node`.  This apparently usually means that an executable file is being edited while executed. Huh.
    - workaround: downgraded to node 16, yarn 1.21 via `nvm`. Haven't bisected which version is the true culprit here.

**Comment by bikubi** [comment]
Got it working. Several issues at play.

- Python: still using 3.10 via pyenv
- Python deps: had to downgrade torch to avoid errors re: various cublas/cuda so-files "missing from system path". See commit linked above. Maybe related to https://github.com/pytorch/pytorch/issues/100974
- Yarn issue: `/usr/bin/env: 'node': Text file busy` apparently points to a problem with new Arch kernel. Downgrading 6.9→6.8 per [this comment on docker-node](https://github.com/nodejs/docker-node/issues/1912#issuecomment-2121246625) fixed this. Wow.
- Yarn footgun: I re-created the whole setup in a new directory. Yarn kept symlinks to the *old* directory in, thru several `rm -rf node_modules` and such. Quick solution was to `rm ~/.config/yarn/link/froide-*`; `yarn unlink` would be proper? Symptoms: `makerequest.js` wasn't transpiled, keeping all `import foo from 'foo-no-extension'` modules intact. This resulted in (uncircumventable) CORS errors in Firefox and 404s in a lowered-security Chromium, resp.

I can't really tell if any of this is relevant to anybody else (in the future), so I'm not closing the issue just yet.

**Comment by krmax44** [comment]
Most of these should be resolved by new tooling.
