### ISSUE TITLE
Dev setup missing (a check for) ocrmypdf?

### ISSUE THREAD

**Issue by bikubi** [okfde/fragdenstaat_de#519]
Document uploader images-to-PDF conversion failed silently (for me), no warnings.
The POST request is successful, and returns an `id` with file path to a PDF, but the object+file does not exist, it is immediately removed.

Cause: `convert_images_to_pdf_task` <https://github.com/okfde/froide/blob/main/froide/foirequest/tasks.py#L254> fails because the `shell_call` to `ocrmypdf` fails in <https://github.com/okfde/django-filingcabinet/blob/main/src/filingcabinet/pdf_utils.py#L388>.

I can see a reference to ocrmypdf [in dev.nix](https://github.com/okfde/fragdenstaat_de/blob/main/dev.nix#L54); locally I had to install it via package manager, plus tesseract language pack(s).

**Comment by krmax44** [comment]
Somewhat solved by https://github.com/okfde/fragdenstaat_de/commit/955d06d9a495a59d9731ab29afbfa908d7a854d6, will further track at https://github.com/okfde/django-filingcabinet/issues/74
