### ISSUE TITLE
FragDieBeratungsgremien

### ISSUE THREAD

**Issue by kirsey** [okfde/fragdenstaat_de#59]
Die Bundesministerien unterhalten fast alle mindestens ein politisches bzw. wissenschaftliches Beratungsgremium. Diese Gremien haben oft ähnliche Aufgaben wie der wissenschaftliche Dienst des Bundestages und ihre gutachterlichen Stellungsnahmen werden bisher nur selten veröffentlicht. Eine Übersicht dieser Gremien kann auf Seite 2 der BT-Drucksache 16/4102 (http://dipbt.bundestag.de/doc/btd/16/041/1604102.pdf) gefunden werden. Eine systematische Veröffentlichung dieser Gutachten würde einen weiteren bedeutsamen Sieg für die politische Transparenz bedeuten.

**Comment by arnese** [comment]
Die meisten der Gremien sollten leider nicht per IFG zugänglich sein.

**Comment by kirsey** [comment]
Welche Gründe sprechen aus deiner Sicht gegen einen Zugang mittels IFGs?

**Comment by arnese** [comment]
Informationspflichtig sind 
nach § 1 Abs. 1 S. 1 IFG alle „Behörden des Bundes“. Der Behördenbegriff entspricht dem des § 1 
Abs. 4 VwVfG.7 Er umfasst alle Stellen, die Aufgaben der öffentlichen Verwaltung wahrnehmen. 
In erster Linie deklaratorischer Natur ist daher der anschließende Satz 2 des § 1 Abs. 1 IFG, wonach
 das IFG auch für „sonstige Bundesorgane und -einrichtungen gilt […], soweit sie öffentlichrechtliche
 Verwaltungsaufgaben wahrnehmen“. 

Beratungen sind keine öffentlich-rechtlichen Verwaltungsaufgaben, Behörden oder Bundesorgane sind die meisten Gremien auch nicht.

**Comment by kirsey** [comment]
Wir können doch beim entsprechenden Ministerium die Gutachten des Beratungsgremiums erfragen, oder habe ich da irgendwas übersehen? Letztendlich wird ja jedes Gremium seine Gutachten beim entsprechenden Ministerium einreichen.

**Comment by arnese** [comment]
Okay - ich weiß gar nicht, wer von denen Gutachten erstellt. Frag doch mal ein paar an und dann schauen wir weiter, ob sich daraus was ergibt!

**Comment by arnese** [comment]
Eine Übersicht der Gremien gibt es hier: https://sehrgutachten.de/bt/wd3/327-10-wissenschaftliche-beratungsgremien-bei-der-bundesregierung-und-im-bundestag

**Comment by kirsey** [comment]
Ich habe jetzt viele Rückmeldungen zu meinen IFG Anträgen an die Beratungsgremien erhalten und insgesamt lässt sich eine geringe Aktivität der Gremien feststellen. Eine gutes Beispiel für die Veröffentlichung von Gutachten ist der wissenschaftliche Beirat des BMF: (http://www.bundesfinanzministerium.de/Web/DE/Ministerium/Wissenschaftlicher_Beirat/Gutachten_und_Stellungnahmen/gutachten_und_stellungnahmen.html)
oder der SRU des BMU:
http://www.umweltrat.de/DE/Publikationen/publikationen_node.html
Wäre es nicht sinnvoll diese Gutachten bei sehrgutachten.de mit einzubinden?

**Comment by arnese** [comment]
Migrated to https://github.com/okfde/sehrgutachten/issues/7
