### ISSUE TITLE
Endung bei PDF-Dateien 

### ISSUE THREAD

**Issue by HappyPony** [okfde/fragdenstaat_de#62]
in dieser Anfrage https://fragdenstaat.de/a/16268 hat die Behörde PDF-Dateien gesendet. In beiden Dateien ist nach  ".pdf" im Dateinamen eine kryptische Zeichenfolge angehängt. Meine Frage: wurden die PDF-Dateien mit so einem kryptischen Schwanz von der Behörde so erstellt oder hat der fragdenstaat.de-Server den Dateinamen verunstaltet?

**Comment by arnese** [comment]
Das ist ein Formatierungsproblem zwischen Behörde und FragDenStaat - die Datei wurde als PDF losgeschickt. Wir arbeiten dran.
