### ISSUE TITLE
nice-to-have: Trefferliste fragdenstaat.de chronologisch sortieren

### ISSUE THREAD

**Issue by HappyPony** [okfde/fragdenstaat_de#63]
Es wäre sehr hilfreich, wenn ich eine Trefferliste wie https://fragdenstaat.de/suche/?q=ttip chronologisch sortieren könnte. So k.m. sich und der Behörde u.U. die oder andere Anfrage sparen. Im Glücksfall wäre es doch nur ein zusätzlicher Parameter, der in der Datenbankabfrage gesetzt werden muß ;-).

**Comment by arnese** [comment]
Diese Issues betreffen das deutsche Theme FragDenStaat. Grundsätzliche Issues betreffen die Software Froide. Dies ist bereits hier referenziert: https://github.com/stefanw/froide/issues/171
