### ISSUE TITLE
nice-to-have: Empfangsbestätigungslink-Feature

### ISSUE THREAD

**Issue by HappyPony** [okfde/fragdenstaat_de#64]
ich rege an, dass das _fragdenstaat.de_-System im Text der Anfrage einen Empfangsbestätigungs-Verweis mitschickt.
* im Verweis "Bitte bestätigen Sie den Eingang  dieser Anfrage --> hier klicken" im Text der Anfrage mitsenden 
* es bietet sich an einer Standard-Schnittstelle bedienen und das Feature mit _Message Disposition Notification_ zu realisieren

Mir ist nämlich mehrmals passiert, dass die Behörde als Antwort auf "Sie haben die Antwortfrist überschritten" antwortet:
> eine Anfrage XYZ ist uns unbekannt.

1. Message Disposition Notification - https://de.wikipedia.org/wiki/Message_Disposition_Notification
2. Empfangsbestätigungen - https://www.thunderbird-mail.de/wiki/Empfangsbest%C3%A4tigungen_%28MDN%29

**Comment by arnese** [comment]
Grundsätzlich sinnvoll - sollte allerdings über Prüfung der Zustellung durch Mailserver geschehen.

**Comment by arnese** [comment]
Dies ist Issue für Software Froide, nicht fürs Themen.
