### ISSUE TITLE
nice-to-have: Empfangsbestätigung-Wecker 

### ISSUE THREAD

**Issue by HappyPony** [okfde/fragdenstaat_de#65]
ich rege an, dem Eigentümer eines _fragdenstaat.de_-Accounts ein Empfangsbestätigung-Wecker zur Verfügung zu stellen:

- bspw. wenn nach einer Woche die Behörde keine Bestätigung gesendet hat, eine EMail dem Anfrager senden "_Empfangsbestätigung für die Anfrage XYZ fehlt_"
- Ideal wäre ein Menüpunkt/ Option im "_Nachricht schreiben_"-Menü "_Empfangsbestätigung anfordern_" mit einem vorgefertigten Textbaustein

Mir ist nämlich mehrmals passiert, dass die Behörde als Antwort auf "Sie haben die Antwortfrist überschritten" antwortet:
> eine Anfrage XYZ ist uns unbekannt.

1. Empfangsbestätigungslink-Feature - #64

**Comment by arnese** [comment]
Dies lässt sich über Fristeneinstellung teilweise schon regeln. Ansonsten erscheint dieses Feature zu komplex. Sinnvoller ist automatische Zustellungsbenachrichtigung.
