### ISSUE TITLE
“Sie haben die Begrenzung von 15 Anfragen in 1 Woche überschritten"

### ISSUE THREAD

**Issue by HappyPony** [okfde/fragdenstaat_de#66]
Ich dürfe gestern eine neue Anfrage https://fragdenstaat.de/a/16830 erstellen, als  ich aber versucht habe, der Behörde in der Anfrage https://fragdenstaat.de/a/16779 eine  Nachricht zu senden, bekam ich eine Meldung:
> Sie haben die Begrenzung von 15 Anfragen in 1 Woche überschritten

Details zu der Meldung "Sie haben die Begrenzung von 15 Anfragen in 1 Woche überschritte" s. https://pod.geraspora.de/posts/4826552.

Ich bin sehr an Informationen interessiert:
* wie _fragdenstaat.de_-System das Ereignis _"Sie haben die Begrenzung von 15 Anfragen in 1 Woche überschritten"_ im Account eines fragdenstaat.de-Nutzers _fragdenstaat-Troll_ erkennt?
* wie _fragdenstaat.de_-System das Ereignis "_Kommunikationssperre für den fragdenstaat-Troll aufheben_" erkennt?
* wo kann ich eine Anleitung für die fragdenstaat.de-Nutzer für den Umgang mit dem “Sie haben die Begrenzung von 15 Anfragen in 1 Woche überschritten"- Ereignis lesen? 
* Die Sperre der Kommunikation ist ein gravierender Eingriff in die Handlungsfreiheit eines Menschen und mich interessiert auch, ob bei der Beauftragung der entsprechenden Programm-Module mit eindeutiger Überwachungsfunktionalität im _fragdenstaat.de_-System - s. unten - die Projektverantwortlichen sich Gedanken darüber gemacht haben, ob derartige Überwachungs-"Features" mit den übergeordneten _fragdenstaat.de_- Projektzielen vereinbar sind.

**um die Bearbeitung meiner Anfragen, die Kommunikation mit den Behörden im Zusammenhang mit den Anfragen auf  fragdenstaat.de planen zu können**. Am einfachsten und zeitsparendsten für beide Seiten wäre, wenn Sie mir eine Beschreibung für den Programmierauftrag für die Module:
> das Ereignis "Sie haben die Begrenzung von 15 Anfragen in 1 Woche überschritten" erkennen

> das Ereignis "Kommunikationssperre für den  fragdenstaat-Troll aufheben

und die Verweise zu den Modulen
> das Ereignis "Sie haben die Begrenzung von 15 Anfragen in 1 Woche überschritten" erkennen

> das Ereignis "Kommunikationssperre für den  fragdenstaat-Troll aufheben

 im https://github.com geben könnten.

1. Wie Open Knowledge Foundation Deutschland e.V. sich zum willfährigen Türhüter des Staates etabliert hat, 16.05.2016 - http://telefonradio-plus.sprechrun.de/index.php?id=4103

**Comment by arnese** [comment]
Das Feature existiert für alle Nutzer.
Ein "gravierender Eingriff in die Handelsfreiheit eines Menschen" wäre das Verbüßen einer Gefängnisstrafe. Ein Feature in einer Open-Source-Software zählt nicht in diese Kategorie.

HappyPony, dies ist ein gemeinnütziges Projekt. Wenn du in diesem Ton mit uns kommunizierst, ist niemandem geholfen. Wir helfen gerne, aber nicht, wenn du uns als "willfährige Türhüter des Staates" beschimpft. Du kannst das Projekt gerne selbst bei dir aufsetzen.

**Comment by HappyPony** [comment]
Danke für eine Rückmeldung.
> HappyPony, dies ist ein gemeinnütziges Projekt. Wenn du in diesem Ton mit uns kommunizierst, ist niemandem geholfen. 

Auch und insbesondere in einem gemeinnützigen Projekt sind die Projektträger dazu verpflichtet, sich an die Versprechen zu halten, die der Projektträger beim Werben um die Spenden mit der Bekanntmachung der Projektziele gemacht hat.

Und wenn OKFN als Projektträger von den Steuergeldern profitiert, dann hat er nach meiner Auffassung eine besondere Verantwortung. Sie haben mir leider in der Sache “_Sie haben die Begrenzung von 15 Anfragen in 1 Woche überschritten"_ keine Antwort gegeben.

**Comment by arnese** [comment]
Ja, HappyPony, wir kommunizieren ja gerne. Aber der Ton muss trotzdem freundlich bleiben.
Das System zählt die Anzahl der Nachrichten. Bei 15 Anfragen innerhalb von sieben Tagen muss eine Pause eingelegt werden.
Das Feature ist u.a. hier: https://github.com/okfde/fragdenstaat_de/blob/b1a241ea019f7e5d480a2dbdb64d44aff5390de3/fragdenstaat_de/settings.py, Zeile 117.
