### ISSUE TITLE
EMail auf fragdenstaat@lists.okfn.org nicht versendet

### ISSUE THREAD

**Issue by HappyPony** [okfde/fragdenstaat_de#67]
aus irgendeinem Grund wurde meine EMail vom 15.05.2016 auf der
FragDenStaat-Mailingliste nicht versendet - s.
Anhang 1. **Ich würde gern den Grund dafür in Erfahrung bringen**.

Hier [1] habe ich die nicht versendete EMail vom 15.05.2016, 17:15:36 sowie eine Meldung von fragdenstaat-bounces@lists.okfn.org vom 16.05.016, 12:24:26, die mir bescheinigt, dass ich ein als Abonnent bei fragdenstaat@lists.okfn.org bin, bereitgestellt.

[1] [okfn-de] fragdenstaat.de: "Sie haben die Begrenzung von 15 Anfragen in 1 Woche überschritten", 16.05.2016, 14:26:59  https://lists.okfn.org/pipermail/okfn-de/2016-May/001491.html

**Comment by arnese** [comment]
Hallo HappyPony, das ist kein Issue der Software und deswegen hier fehl am Platz. Bitte sende eine E-Mail an info@fragdenstaat.de.
