### ISSUE TITLE
001II_0551.pdfname0iso-8859-149582D3731305F3030312049495F303535312Ename1706466 

### ISSUE THREAD

**Issue by HappyPony** [okfde/fragdenstaat_de#68]
zum Verständnis - korrigiert momentan das fragdenstaat_de-Team die Endungen einzeln?? Wie hier 

- "Bahn gibt Kundendaten weiter" [#16752] - https://fragdenstaat.de/a/16752

**Comment by arnese** [comment]
Ja. Gerade gibt es keine einfache technische Lösung, deswegen eine manuelle.

**Comment by HappyPony** [comment]
Ich bitte bei dieser Datei https://fragdenstaat.de/files/foi/50765/IX-710_001II_0551.pdfname0iso-8859-149582D3731305F3030312049495F303535312Ename1706466 die Endung auf .PDF ändern.
