### ISSUE TITLE
Neuer Filter: Vermittlung bei Landesbeauftragten für Datenschutz und Informationsfreiheit

### ISSUE THREAD

**Issue by GiantCrocodile** [okfde/fragdenstaat_de#70]
Ich würde gerne sehen, welche Anträge um Vermittlung bei der oder dem Landesbeauftragten für Datenschutz und Informationsfreiheit gebeten haben. Der Filter sollte reguläre Anträge an diese Behörde ausschließen.

Grund: So kann man leichter sehen, wie andere Vermittlungsverfahren verlaufen sind und wie andere Antragsteller um Vermittlung bitten.

**Comment by arnese** [comment]
Teil von https://github.com/okfde/froide/issues/171
