### ISSUE TITLE
Anhänge in neuem Tab öffnen

### ISSUE THREAD

**Issue by arasabbasi** [okfde/fragdenstaat_de#71]
Anhänge werden im gleichen Fenster/Tab geöffnet. Ich finde das unpraktikabel. Meines Erachtens wäre das öffnen der Anhänge in einem neuen Tab handlicher. Mir passiert es immer wieder, dass ich mir den Anhang anschaue, dann den Tab schließe um den Fehler zu merken... Also Tab wiederherstellen und history.back(). 

Wäre nur nice to have.

**Comment by stefanw** [comment]
Mittelfristiges Ziel ist es gerade, eine bessere Dokumentenvorschau hinzubekommen, anstatt direkt auf die Datei zu verlinken. target=_blank sind immer gemischte Gefühle ;)

**Comment by arasabbasi** [comment]
nachvollziehbar, aber man kann nunmal nicht alle Dateiformate in einem kleinen DialogWindow anzeigen. 
Für Pdfs kann man PDFObject empfehlen. aber sonst... was macht man mit docx dateien und so.das 

Btw. Das PDF-Schwärzungstool ist richtig gut

**Comment by stefanw** [comment]
Lange her, aber es gibt jetzt eine schönere Dokumentenvorschau, zumindestens für PDFs.
