### ISSUE TITLE
Bürgeranfrage und Erklärungsmöglichkeit durch die Behörde?

### ISSUE THREAD

**Issue by arasabbasi** [okfde/fragdenstaat_de#72]
Ich möchte die Möglichkeit der Bürgeranfrage und der Erklärungsmöglichkeit ansprechen. Vor dem IFG wurden einfache Anfragen auch normal als Bürgeranfrage bearbeitet. Sollten wir nicht noch so einen Satz wie folgt noch einbauen?:

"Sollte meine Anfrage ganz oder teilweise nicht aufgrund des IFG/UIG/VIG beantwortbar sein, so bitte ich die Bewertung meiner Anfrage als einfache Bürgeranfrage zu werten und Auskunft zu geben. Gerne kann die Behörde oder das zuständige Fachreferat eine Erklärung zu meiner Anfrage abgeben."

Ich kriege nämlich idR bei den Antworten vom Auswärtigen Amt meist auch eine zusätzliche Erklärung. Die Erklärungen sind manchmal besser/verwertbarer als die übersendeten Akten(bestandteile).

Aras

**Comment by arnese** [comment]
Gute Idee - ich bin mir noch nicht sicher, ob es den Text zu sehr aufblähen würde - wir nehmen uns den aber sowieso bald nochmal vor und lassen das mit einfließen.

**Comment by arnese** [comment]
Die Anfrage als Bürgeranfrage scheint - siehe Bayern - keinen zusätzlichen Mehrwert zu bringen.
