### ISSUE TITLE
Generierung von lächerlichen privaten E-Mail-Adressen unterbinden

### ISSUE THREAD

**Issue by GiantCrocodile** [okfde/fragdenstaat_de#74]
Die generierten privaten E-Mail-Adressen sollten nicht lächerlich sein. Dies tut dem Eindruck des Anfragendem gegenüber dem Sachbearbeiter nicht gut und ist zudem schädlich für die notwendige Ernsthaftigkeit bei der Anfrage.

Beispiel: "lilith_the_daughter_of_dracula_...@echtemail.de"

**Comment by arnese** [comment]
Sehe ich anders. Antworten an diese Art von E-Mail zeigt, dass Verhalten von Behörden falsch ist.

**Comment by jfilter** [comment]
Sie antworten dann halt nicht, Arne. Aber genau das war das Ziel, oder? Ich glaube schon, dass man bessere private E-Mail-Adressen faken kann, um zu tricksen.

**Comment by stefanw** [comment]
Es geht darum zu zeigen, dass die offizielle E-Mail-Adresse der Anfrage `a.semsrott.[...]@` seriöser ist, als eine 'private' Mailadresse. Diese 'private' sollte es ja gar nicht geben müssen. Die echtemail.de-Adressen finde ich schon ziemlich authentisch.

Außerdem scheint [Lilith, die Tochter Draculas](https://en.wikipedia.org/wiki/Lilith_(Marvel_Comics)), ziemlich cool zu sein.

**Comment by jfilter** [comment]
Okay, die Metaebene in diesem Kunstprojekt habe ich nicht gesehen.
