### ISSUE TITLE
Verweise verursachen eine "403 - Verboten"-Meldung

### ISSUE THREAD

**Issue by HappyPony** [okfde/fragdenstaat_de#75]
Hallo,

ich habe vor einiger Zeit diese Verweise

https://fragdenstaat.de/anfrage/ifg-verwaltungsaufwand/
https://fragdenstaat.de/anfrage/umgang-mit-ifg-anfragen-durch-ressorts-der-bundesregierung/

in meiner Lesezeichensammlung abgelegt. Jetzt bekomme ich die Meldung

> 403 - Verboten
> 
> Sie haben versucht einen Teil der Seite aufzurufen, für den Sie keine Rechte haben oder Sie haben einen zusätzlichen Sicherheitsmechanismus ausgelöst.

beim Aufruf von diesen Seiten.  Unabhängig davon, 

- ob ich die Webseiten per https:// oder http:// aufrufe
- mit einem Slash am Ende der URL oder ohne Slash

Wurde die Verlinkung auf fragdenstaat.de in der Zwischenzeit geändert? Gibt es evtl. eine Regel, die es erlaubt, eine URL für den neuen Speicherort der Webseite anhand der alten URL zu ermitteln?

**Comment by arnese** [comment]
Nein, die beiden Anfragen wurden zwischenzeitlich gelöscht.
