### ISSUE TITLE
Bedarf für eine optische Überarbeitung?

### ISSUE THREAD

**Issue by Algram** [okfde/fragdenstaat_de#76]
Hallo FragDenStaat,

gibt es Bedarf für eine kleine optische Überarbeitung der Seite? Größtenteils würde ich mich auf konsistente Abstände, Farben und Größen konzentrieren.

Wenn es Bedarf gibt dann kommt von mir dazu ein Pull Request.

**Comment by arnese** [comment]
Hallo @Algram! Ja, ja, ja! Gerne! Wenn du dazu Fragen hast, meld dich auch gern bei mir: arne.semsrott@okfn.de
