### ISSUE TITLE
Link zur Wikimedia-Kooperation bei Gebühren

### ISSUE THREAD

**Issue by arnese** [okfde/fragdenstaat_de#77]
Es sollte bei Anwählung von "wurde aus Kostengründen zurückgezogen" und der Eingabe von Gebühren ins Gebührenfeld einen Hinweis auf unsere Kooperation mit Wikimedia geben:

"Schon gewusst? Wikimedia übernimmt Gebühren für Anfragen, sofern sie gerechtfertigt sind und Inhalte u.a. in die Wikipedia eingepflegt werden. Mehr Informationen: https://de.wikipedia.org/wiki/Wikipedia:F%C3%B6rderung/Geb%C3%BChrenerstattungen_f%C3%BCr_Anfragen_nach_Informationsfreiheitsgesetz "

**Comment by GiantCrocodile** [comment]
Gibt es schon Beispiele, wer davon profitiert in der Vergangenheit hat? Ich sehe nur sehr sehr wenige Fälle, die überhaupt von Wikipedia-Interesse sein können.

**Comment by Unterstrichmoepunterstrich** [comment]
Also ich bin ja in der Wikipedia aktiv und ich nutze regelmäßig FdS zur Untermauerung von Fakten, auch wenn das bisher (leider?) nur Anfragen, die nichts gekostet haben.

**Comment by GiantCrocodile** [comment]
Im Erstattungsformular heißt es wörtlich: "Ich versichere, alle hier genannten Güter und Leistungen im Auftrag und
zum Vorteil von Wikimedia Deutschland e.V. / der Gemeinnützigen Wikimedia
Fördergesellschaft mbH erworben zu haben. Alle genannten Güter
wurden dem Verein zur alleinigen Nutzung übergeben"

Das klingt für mich überhaupt nicht mit FdS/dem IFG vereinbar. Auch wenn es ein Standardformular ist, so muss es zumindest passen oder angepasst werden. Eine alleinige Nutzung der Güter [hier: Informationen] ist ausgeschlossen.

**Comment by arnese** [comment]
Ist jetzt hier: https://github.com/okfde/froide/issues/277
