### ISSUE TITLE
Änderungen "Post erhalten"

### ISSUE THREAD

**Issue by arnese** [okfde/fragdenstaat_de#78]
- [x] Alle Pflichtfelder sollten mit einem * versehen werden
- [x] Die Felder, die nach der Fehlermeldung noch fehlen, sollten Rot markiert werden.
- [x] Entfernung Absendername

**Comment by stefanw** [comment]
Form errors are well marked, Absendername is now optional.

**Comment by arnese** [comment]
Absender (Behörde) fehlt jetzt in Firefox 58 :)

![](https://screenshotscdn.firefoxusercontent.com/images/2343ea34-5f50-4ac7-931d-7b1d52a9c062.png)

**Comment by stefanw** [comment]
I believe that was a temporary JS bug.
