### ISSUE TITLE
Dokumenten-Upload: mehrere Dokumente

### ISSUE THREAD

**Issue by ilf** [okfde/fragdenstaat_de#80]
Bisher kann man immer nur ein Dokument auf einmal hochladen. Es wäre schöner, wenn man gleich mehrere hochladen kann, sonst wird das schnell nervig.

Im HTML dürfte das mit einem simplen `<input multiple>` bei `<input name="scan" required="" id="id_scan" type="file">` zu machen sein. Wie das im Django geht, weiss ich nicht. Aber das bekommt ihr sicher in ein paar wenigen Minuten hin. :)

**Comment by stefanw** [comment]
[Alle Anhänge-Uploads akzeptieren jetzt mehrere Dateien.](https://github.com/okfde/froide/commit/a48b71bfe31afc478e8571b20424ec37433e4389)
Hurra! Guck mal, ob's das tut, was es soll.

**Comment by ilf** [comment]
Ich habe gerade keine IFG-Antwort mit mehreren Dokumenten, aber ein Dummy-Test ohne Absenden scheint soweit zu funktionieren. Bekommst ein 🍺!

**Comment by ilf** [comment]
Das geht wieder nicht? Zumindest sehe ich gerade `<input name="files" required="" id="id_files" type="file">` im Source und mein Browser lässt mich nur eine Datei auswählen.

**Comment by arnese** [comment]
Das geht beim Neuerstellen von einer Antwort, aber derzeit nicht bei einer schon erstellten Antwort

**Comment by stefanw** [comment]
Sollte jetzt auch bei existierenden Antworten funktionieren.

**Comment by ilf** [comment]
Danke, tut. Theoretisch. Praktisch gibt nginx den Fehler "413 Request Entity Too Large". Sind 85 MB. Neues Ticket? Zu groß für normale Accounts?

**Comment by stefanw** [comment]
[Max Upload sind gerade 50 MB](https://github.com/okfde/fragdenstaat.de-ansible/blob/master/roles/nginx/templates/nginx_config.j2#L60), vielleicht spaltest du das einmal auf?

**Comment by ilf** [comment]
Danke, done. <3
