### ISSUE TITLE
referer wieder benötigt

### ISSUE THREAD

**Issue by ilf** [okfde/fragdenstaat_de#81]
Mit deaktivierttem Referer kommt wieder die Fehlermeldung: 

> 403 - Verboten
> Sie haben vermutlich Ihre Browser-Cookies deaktivert, allerdings brauchen Sie Cookies für diese Seite! Cookies werden auf dieser Seite nur über eine sichere Verbindung gesendet. Der technische Grund für diesen Fehler ist: Referer checking failed - no Referer.

Mit Referer geht's. In zwei Browsern getestet.

https://github.com/okfde/fragdenstaat_de/blob/master/fragdenstaat_de/theme/ilf_middleware.py ist noch da.

1. Wird die auch verwendet?
2. Funktioninert die noch?

These: Das hat was mit dem Ubuntu Update zu tun?

**Comment by stefanw** [comment]
Fixed by 9eff363ffbec7bde3e51232defda7137ca462689

Die `ilf_middleware` war aus der production Konfiguration geflogen.

**Comment by ilf** [comment]
Tut, danke!
