### ISSUE TITLE
Dem Anfrager bei den erhaltenen E-Mails die Absendeadresse anzeigen

### ISSUE THREAD

**Issue by erlendorf** [okfde/fragdenstaat_de#82]
Dem Anfrager sollte in der Korrespondenz-Ansicht für jede erhaltene E-Mail jeweils die Absendeadresse angezeigt werden.  Z.B. als Tooltip.

Grund:

Wenn der Anfrager eine neue E-Mail schreiben will, so muss er auswählen, an welche E-Mailadresse er schreiben will.  Würde der Vorschlag implementiert, so könnte er schauen, von welcher Adresse die letzte E-Mail kam, und die Entscheidung, an welche Adresse er schreiben soll, würde einfacher fallen.

**Comment by arnese** [comment]
Das ist inzwischen implementiert als Tooltip.
