### ISSUE TITLE
Bayerisches Archivgesetz

### ISSUE THREAD

**Issue by erlendorf** [okfde/fragdenstaat_de#83]
Wurde grade von einem Mitarbeiter einer bayrischen Einrichtung auf folgendes aufmerksam gemacht:

Das Bayerische Archivgesetz ist ein bereichspezifisches Datenschutzgesetz und regelt grundsätzlich den Zugang zu Archivgut. 

Man findet das Gesetz und die darauf basierende Archivbenützungsordnung leicht im Netz, beispielsweise [auf der Homepage der Staatlichen Archive Bayerns](http://www.gda.bayern.de/fachinformationen/aufgaben-und-organisation/).

Evtl. kann man das in der Hilfe erwähnen, und möglicherweise gibt es ja noch mehr solcher Gesetze, die wir ausfindig machen könnten.

**Comment by arnese** [comment]
Ist das relevant? Dies betrifft Daten und Dokumente, die älter als 30 Jahre sind. Anfragen nach solchen Dokumenten sind über FragDenStaat recht selten.
