### ISSUE TITLE
Nachrichten eines Tages in umgedrehter Reihenfolge, in der sie eingestellt wurden

### ISSUE THREAD

**Issue by erlendorf** [okfde/fragdenstaat_de#85]
Die Nachrichten vom 27. Juni 2017 [in dieser Anfrage](https://fragdenstaat.de/anfrage/gefangenenpersonalakte-adolf-hitler-und-aufnahmebuch-landsberg-a-lech/#nachricht-70349) wurden außerhalb des FragDenStaat-Systems gemacht, von mir aber in der Reihenfolge, in der sie gesendet wurden, auch nacheinander eingestellt. Kurioserweise werden sie jetzt in genau umgedrehter Reihenfolge angezeigt.

**Comment by arnese** [comment]
Danke! Fehler ist bekannt und wird hier bearbeitet: https://github.com/okfde/froide/issues/213
