### ISSUE TITLE
Reihenfolge bei händisch eingetragenen Antworten

### ISSUE THREAD

**Issue by torfsen** [okfde/fragdenstaat_de#88]
Ich habe eben eine Antwort einer Behörde und meine Antwort darauf händisch in FDS eingepflegt. Beide wurden am gleichen Tag versendet, so dass FDS nun meine Antwort auf die Antwort vor der Antwort der Behörde anzeigt, obwohl ich die Antwort der Behörde zu erst (erhalten und) eingepflegt habe. Siehe die zwei Schreiben vom 24.10.2017 in folgender Anfrage: https://fragdenstaat.de/anfrage/weisungen-des-jobcenters-jobcenter-landkreis-reutlingen/#nachricht-77446.

**Comment by arnese** [comment]
Jap, danke! Arbeiten wir dran. Haben wir hier schon als Issue: https://github.com/okfde/froide/issues/213
