### ISSUE TITLE
Keine Kommas nach Grußformel

### ISSUE THREAD

**Issue by GiantCrocodile** [okfde/fragdenstaat_de#90]
"Mit freundlichen Grüßen," <- Komma muss weg.

**Comment by jonazc** [comment]
wurde wohl erledigt: https://github.com/okfde/fragdenstaat_de/commit/54da182502621c5cdad8546f590a6dbbc53fd750#diff-c3f2fc45290d7057ae8c0129097fd396 <- Issue kann zu :)

**Comment by GiantCrocodile** [comment]
Danke für die Info @jonazc!
