### ISSUE TITLE
Anfragen melden

### ISSUE THREAD

**Issue by jonazc** [okfde/fragdenstaat_de#91]
Es sollte eine Möglichkeit geben Anfragen zu melden, Beispielsweise wenn offensichtlich unabsichtlich private Daten öffentlich einsehbar sind.

**Comment by GiantCrocodile** [comment]
Bisher kann man E-Mails an die allgemeine FragDenStaat.de-E-Mail-Adresse senden. Das klappt super und es wird sich in der Regel schnell um Anliegen gekümmert. Unabhängig dessen fände ich das auch gut - am Besten mit Dropdown-Auswahl für den Grund, damit es schnell geht:

- private Daten schwärzen (Unterschriften, Namen, Adressen),
- Anhang nochmal zurücksetzen zwecks erneut schwärzen,
- Missbrauch von FragDenStaat (Spam, Reichsbürger-Unsinn),
- Anfrage nochmal absenden, nach E-Mail-Adresse der Behörde korrigieren.

**Comment by arnese** [comment]
Das ist hier aufgeführt: https://github.com/okfde/froide/issues/27
