### ISSUE TITLE
Dateinamen anonymisierung?

### ISSUE THREAD

**Issue by jonazc** [okfde/fragdenstaat_de#92]
Ich habe bei einer Anfrage eine Datei erhalten in deren Bezeichnung mein Name enthalten ist. Wird der Dateiname bei Veröffentlichung automatisch anonymisiert? Oder kann das irgendwie manuell gemacht werden?

**Comment by stefanw** [comment]
Der Name wird anonymisiert. Das kann im Einzelfall schief gehen (andere Umlaute, Sonderzeichen etc.). Bitte konkretes Beispiel nennen oder an den Support wenden.

**Comment by stefanw** [comment]
Die Anonymisierung wurde verbessert: https://github.com/okfde/froide/commit/d88378395c7e5c35fdaec4a1a6bdee764622d9c1

**Comment by jonazc** [comment]
danke :)
