### ISSUE TITLE
Eskalation des Nachrichtentextes nach drei Monaten

### ISSUE THREAD

**Issue by arnese** [okfde/fragdenstaat_de#93]
Hat ein Antragssteller drei Monate nach der Anfrage noch keine Antwort erhalten, sollte der vorformulierte Remindertext den Zusatz erhalten: "Ich weise Sie darauf hin, dass inzwischen eine Untätigkeitsklage möglich ist."

**Comment by arasabbasi** [comment]
Vielleicht sowas

> Ich weise Sie daraufhin, dass  drei Monate seit Antragseingang verstrichen sind. Einen zureichenden Grund für die Nichtentscheidung haben Sie nicht geltend gemacht. Somit ist eine Untätigkeitsklage zulässig ist. Gemäß der Rechtsprechung besteht vor Erhebung einer Untätigkeitsklage keine Pflicht den Sachstand des Antrags bei der Behörde zu erfragen. Ungeachtet dessen setze ich Ihnen hiermit letztmalig eine Frist von X Wochen um eine Entscheidung herbeizuführen.

**Comment by arnese** [comment]
migriert nach https://github.com/okfde/fragdenstaat_de/issues/93
