### ISSUE TITLE
Anfragezahl auf Startseite hochsetzen

### ISSUE THREAD

**Issue by arnese** [okfde/fragdenstaat_de#94]
Die Zahl der gesamten Anfragen über FDS sollte auf der Startseite nicht mehr um die Massenkampagnen bereinigt sein, sondern sämtliche Anfragen minus Nicht-IF anzeigen. Kein Grund zur Bescheidenheit :)

**Comment by stefanw** [comment]
Sollen auch die nicht-öffentlichen Anfragen mitgezählt werden?

**Comment by arnese** [comment]
Ja - die gesamte Zahl prominent darzustellen ist wichtig, denke ich.

**Comment by stefanw** [comment]
Ich weiß nicht, was du genau mit der Zahl auf der Startseite meinst. Aber wenn sie in diesem Kontext steht "Suchen Sie in 16432 Anfragen und 12403 Behörden:" dann können wir nicht die nicht-öffentlichen mitzählen (weil man sie ja nicht durchsuchen kann).

**Comment by arnese** [comment]
sieht gut aus jetzt.
