### ISSUE TITLE
Filter für gestellte Anfragen

### ISSUE THREAD

**Issue by eriu** [okfde/fragdenstaat_de#95]
moin moin,

ich würde mir als Erweiterung der Ansicht "ihre Anfragen" bzw. "Anfragen, denen Sie folgende" eine Filtermöglichkeit  wünschen z.B. nach Datum oder Status der Anfrage. Bislang kann man nicht nach einen Symbol (z.B. eingeschlafen oder erfolgreich) sortieren und die z.B. erfolgreichen somit ausblenden.

**Comment by arnese** [comment]
Definitiv. Haben wir hier: https://github.com/okfde/froide/issues/133
