### ISSUE TITLE
Social Media Meta Tags

### ISSUE THREAD

**Issue by jfilter** [okfde/fragdenstaat_de#96]
Make use of social media Tags to a) improve share ability and b) prevent social media sites from guessing which thumbnail to display.

**Comment by jfilter** [comment]
Prevent this: ![Uploading B3163AC6-7C42-4474-9853-9CF3510A306F.jpeg…]()

**Comment by stefanw** [comment]
Good point. Any idea what we could use for Social Media pictures? The logo? A screenshot of the page? Pictures of documents when there are some? A nice picture of the public body (or from the state of the public body)? If we want to be explicit about this, we need to decide. Maybe @arnese @stadine have ideas.

**Comment by stadine** [comment]
Yes! We are currently doing illustrations for freedom of information and FDS. We could also use elements of it for this purpose. We'll have them by mid-February.

**Comment by arnese** [comment]
The logo would be nice, @stefanw

**Comment by arnese** [comment]
Is this still a thing, @jfilter ?

**Comment by jfilter** [comment]
Yes, there are no meta tags for FOI request.

**Comment by benbender** [comment]
Noticed the issue on Twitter sharing a FOI-request lately. Would be nice to have at least `open graph`- and `twitter-card`-tags to improve visibility!

May I ask what if there are any issues holding back the implementation since 2017? If there are any, maybe I could help.

**Comment by stefanw** [comment]
It stalled because we were fruitlessly searching for some way to somehow have images for requests to show on social media.

**Comment by benbender** [comment]
Just take your Logo. Interesting parts would be title/description anyway which could be simply generated dynamically. With properly chosen format, the picture is only roughly a 1/3rd of the space of the preview.

For an idea, just use some text-heavy page (f.e. a stack-overflow-post) and put it in here: 
 * https://cards-dev.twitter.com/validator
 * https://developers.facebook.com/tools/debug/

**Comment by stefanw** [comment]
A fixed version is now deployed. Image does not really fit, but maybe that's for another day.
