### ISSUE TITLE
Antwort an Behörde und Vermittler einschalten geht durcheinander

### ISSUE THREAD

**Issue by amigalemming** [okfde/fragdenstaat_de#97]
Ich hatte in einer Sache (https://fragdenstaat.de/a/25968) erst einen Vermittler eingeschaltet und mir dann überlegt, dass ich doch noch der Behörde antworten könnte. Wenn ich nach Einschaltung des Vermittlers noch "Um eine Antwort an die Behörde zu schreiben klicken Sie hier" anwähle, dann wird als Betreff "Vermittlung ..." eingetragen.

**Comment by stefanw** [comment]
Valider Bug, muss aber noch etwas größer gedacht werden. Manchmal sind mehrere Behörden in einem Thread und man will natürlich den Betreff der letzten Nachricht von oder an diese Behörde referenzieren. Bessere Templates für Antworten mit mehr Hilfe sind angebracht.

**Comment by arnese** [comment]
Wir wollen das auf einer neuen Anfrageseite über unterschiedliche Tabs lösen.

**Comment by arnese** [comment]
Done.
