### ISSUE TITLE
Bestätigungs-E-Mail soll Text der Anfrage oder Nachricht enthalten

### ISSUE THREAD

**Issue by amigalemming** [okfde/fragdenstaat_de#98]
Da FragDenStaat.de ohnehin bei jeder versendeten FragDenStaat-Nachricht eine E-Mail an den Anfrager sendet, könntet ihr da auch gleich den Text der Nachricht mit hineinschreiben? Ich weiß, dass ich mir das ZIP-Archiv für jeden Vorgang herunterladen kann, aber in meiner E-Mail-Box finde ich Sachen doch leichter wieder und das Herunterladen des ZIPs vergesse ich leicht mal.

**Comment by stefanw** [comment]
Prinzipiell ist das möglich, aber die eigenen Anfragen lassen sich ja auch auf FragDenStaat.de selbst durchsuchen: https://fragdenstaat.de/account/

Wir haben damals darauf verzichtet, den Text mitzusenden, um zu verhindern, dass Leute die Benachrichtigungs-E-Mail mit der echten Kommunikation mit der Behörde verwechseln, da diese ja per Design über FragDenStaat.de stattfinden soll.

Vielleicht habe ich den Use Case noch nicht ganz verstanden. Warum möchtest du den Text der Anfrage auch in deinen E-Mails finden, wenn du die Anfrage und ihren Verlauf jederzeit auf FragDenStaat.de nachvollziehen kannst?

**Comment by amigalemming** [comment]
On Fri, 2 Feb 2018, Stefan Wehrmeyer wrote:

> Vielleicht habe ich den Use Case noch nicht ganz verstanden. Warum 
> möchtest du den Text der Anfrage auch in deinen E-Mails finden, wenn du 
> die Anfrage und ihren Verlauf jederzeit auf FragDenStaat.de 
> nachvollziehen kannst?

Eigentlich wäre es besser, wenn überhaupt alle Texte, die ich bei 
fragdenstaat.de eingebe, in der Bestätigungsemail enthalten sind, und wenn 
auch die Antworttexte der Behörden in der E-Mail-Benachrichtigung stehen 
und auch die Kommentare anderer Nutzer. PDFs sollten wegen der Größe 
besser nicht mit versendet werden, aber die reinen Texte schon.

Ich muss hier immer zwischen E-Mail-Programm und Browser wechseln und oft 
genug sehe ich als neu eingetroffene Antwort einfach nur: "Wir haben Ihre 
Anfrage erhalten. Wir werden uns in den nächsten Tagen wieder bei Ihnen 
melden." Oder es ist ein kurzer Kommentar eines anderen Nutzers.

Aber auch bei den selbstgeschriebenen Texten wäre es praktisch, wenn sie 
gleich in der Bestätigungs-E-Mail enthalten sind und nicht nur im 
ZIP-Archiv. Die E-Mail bekomme ich sofort und automatisch. Das ZIP-Archiv 
bekomme ich erst bei "Download" und muss es dann noch aus dem 
Download-Verzeichnis in das richtige Verzeichnis verschieben. 
Automatisieren mit wget kann ich auch nicht einfach, weil ich zum 
Herunterladen angemeldet sein muss.

Ein genügend langer Einleitungstext in der Fragdenstaat-E-Mail könnte 
Benutzer daran hindern, daran zu glauben, dass die Behördenkommunikation 
über das benutzereigene E-Mail-Konto geführt wird.

**Comment by arnese** [comment]
Das halte ich nicht für sinnvoll. Teil des FragDenStaat-Konzepts ist die Kommunikation über die Plattform. Ein Download der Daten erscheint mir ausreichend.

**Comment by amigalemming** [comment]
On Fri, 2 Feb 2018, arnese wrote:

> Das halte ich nicht für sinnvoll. Teil des FragDenStaat-Konzepts ist die 
> Kommunikation über die Plattform. Ein Download der Daten erscheint mir 
> ausreichend.

Neue Kommentare zu GitHub-Tickets bekomme ich übrigens auch als E-Mail 
zugeschickt. Sehr sehr praktisch! Ich kann sie sogar über mein 
E-Mail-Programm beantworten, soweit will ich bei fragdenstaat.de gar nicht 
gehen.

Manuelle Downloads bedeuten praktisch stets unaktuelle heruntergeladene 
Archive. Es setzt sich doch niemand hin und klickt nach jeder neuen 
Nachricht den Download an und sortiert das Archiv neu in seine Sammlung 
ein. Ich habe meine Daten gerne auf meinem Rechner, nicht auf einem fernen 
Server, der manchmal nicht erreichbar ist und manchmal auch ganz 
aufgegeben wird.

**Comment by arnese** [comment]
Ein Sammeldownload für alle Anfragen wird bevorzugt.
https://github.com/okfde/froide/issues/207
